In [1]:
!pip install -U spacy pandas openpyxl matplotlib

Requirement already satisfied: spacy in /usr/local/lib/python3.13/dist-packages (3.8.16)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (3.0.6)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.11.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.13/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (0.27.2)
Requirement already satisfied: click<9.0.0,>=8.2.1 in /usr/local/lib/python3.13/dist-packages (from spacy) (8.5.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.13.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from spacy) (80.10.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: pillow>=9 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.7.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.5)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.25.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.21.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.4.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

In [2]:
import spacy
import pandas as pd

print("spaCy version:", spacy.__version__)
print("Pandas version:", pd.__version__)

spaCy version: 3.8.16
Pandas version: 3.0.6

In [3]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 23.0 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [4]:
import spacy

nlp = spacy.load("en_core_web_sm")

print("spaCy model loaded successfully!")

spaCy model loaded successfully!

In [6]:
from google.colab import files

uploaded = files.upload()

Saving cbc_medexplain.csv to cbc_medexplain.csv

In [4]:
import pandas as pd

cbc_df = pd.read_csv("cbc_medexplain.csv")

In [9]:
cbc_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 48 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   report_id        100 non-null    str
 1   raw_report_text  100 non-null    str
 2   overall_status   100 non-null    str
 3   HGB_value        100 non-null    float64
 4   HGB_unit         100 non-null    str
 5   HGB_ref_low      100 non-null    float64
 6   HGB_ref_high     100 non-null    float64
 7   HGB_status       100 non-null    str
 8   HCT_value        100 non-null    float64
 9   HCT_unit         100 non-null    str
 10  HCT_ref_low      100 non-null    float64
 11  HCT_ref_high     100 non-null    float64
 12  HCT_status       100 non-null    str
 13  PLT_value        100 non-null    int64
 14  PLT_unit         100 non-null    str
 15  PLT_ref_low      100 non-null    float64
 16  PLT_ref_high     100 non-null    float64
 17  PLT_status       100 non-null    str
 18  MCV_value        100 non-null    float64
 19  MCV_unit         100 non-null    str
 20  MCV_ref_low      100 non-null    float64
 21  MCV_ref_high     100 non-null    float64
 22  MCV_status       100 non-null    str
 23  MCHC_value       100 non-null    float64
 24  MCHC_unit        100 non-null    str
 25  MCHC_ref_low     100 non-null    float64
 26  MCHC_ref_high    100 non-null    float64
 27  MCHC_status      100 non-null    str
 28  MCH_value        100 non-null    float64
 29  MCH_unit         100 non-null    str
 30  MCH_ref_low      100 non-null    float64
 31  MCH_ref_high     100 non-null    float64
 32  MCH_status       100 non-null    str
 33  RDW_value        100 non-null    float64
 34  RDW_unit         100 non-null    str
 35  RDW_ref_low      100 non-null    float64
 36  RDW_ref_high     100 non-null    float64
 37  RDW_status       100 non-null    str
 38  NE%_value        100 non-null    float64
 39  NE%_unit         100 non-null    str
 40  NE%_ref_low      100 non-null    float64
 41  NE%_ref_high     100 non-null    float64
 42  NE%_status       100 non-null    str
 43  LY%_value        100 non-null    float64
 44  LY%_unit         100 non-null    str
 45  LY%_ref_low      100 non-null    float64
 46  LY%_ref_high     100 non-null    float64
 47  LY%_status       100 non-null    str
dtypes: float64(26), int64(1), str(21)
memory usage: 86.9 KB

In [10]:
cbc_df.head()

,report_id,raw_report_text,overall_status,HGB_value,HGB_unit,HGB_ref_low,HGB_ref_high,HGB_status,HCT_value,HCT_unit,...,NE%_value,NE%_unit,NE%_ref_low,NE%_ref_high,NE%_status,LY%_value,LY%_unit,LY%_ref_low,LY%_ref_high,LY%_status
0,CBC_001,COMPLETE BLOOD COUNT\n\nHemoglobin: 14.2 g/dL ...,Abnormal,14.2,g/dL,12.0,16.0,Normal,41.0,%,...,83.6,%,40.0,70.0,High,14.1,%,20.0,40.0,Low
1,CBC_002,COMPLETE BLOOD COUNT\n\nHb: 11.9 g/dL Referen...,Abnormal,11.9,g/dL,12.0,16.0,Low,35.5,%,...,59.4,%,40.0,70.0,Normal,31.1,%,20.0,40.0,Normal
2,CBC_003,COMPLETE BLOOD COUNT\n\nHGB: 11 g/dL Referenc...,Abnormal,11.0,g/dL,12.0,16.0,Low,30.1,%,...,60.1,%,40.0,70.0,Normal,37.9,%,20.0,40.0,Normal
3,CBC_004,COMPLETE BLOOD COUNT\n\nHemoglobin: 14.5 g/dL ...,Abnormal,14.5,g/dL,12.0,16.0,Normal,42.5,%,...,79.0,%,40.0,70.0,High,14.3,%,20.0,40.0,Low
4,CBC_005,COMPLETE BLOOD COUNT\n\nHb: 14.1 g/dL Referen...,Normal,14.1,g/dL,12.0,16.0,Normal,40.7,%,...,57.0,%,40.0,70.0,Normal,25.8,%,20.0,40.0,Normal

In [11]:
text = """
Patient CBC report shows hemoglobin 11.2 g/dL,
hematocrit 34%, platelet count 150000 per microliter,
MCV 72 fL, MCH 24 pg, MCHC 31 g/dL,
RDW 15%, neutrophils 65%, and lymphocytes 28%.
"""

In [12]:
doc = nlp(text)
print(doc)

Patient CBC report shows hemoglobin 11.2 g/dL,
hematocrit 34%, platelet count 150000 per microliter,
MCV 72 fL, MCH 24 pg, MCHC 31 g/dL,
RDW 15%, neutrophils 65%, and lymphocytes 28%.

In [13]:
for token in doc:
  print(token.text)

Patient
CBC
report
shows
hemoglobin
11.2
g
/
dL
,


hematocrit
34
%
,
platelet
count
150000
per
microliter
,


MCV
72
fL
,
MCH
24
pg
,
MCHC
31
g
/
dL
,


RDW
15
%
,
neutrophils
65
%
,
and
lymphocytes
28
%
.

In [14]:
for token in doc:
  print(token.text,"+",token.pos_)

 + SPACE
Patient + PROPN
CBC + PROPN
report + NOUN
shows + VERB
hemoglobin + PROPN
11.2 + NUM
g + PROPN
/ + SYM
dL + PROPN
, + PUNCT

 + SPACE
hematocrit + VERB
34 + NUM
% + NOUN
, + PUNCT
platelet + ADJ
count + NOUN
150000 + NUM
per + ADP
microliter + NOUN
, + PUNCT

 + SPACE
MCV + PROPN
72 + NUM
fL + NOUN
, + PUNCT
MCH + PROPN
24 + NUM
pg + PROPN
, + PUNCT
MCHC + PROPN
31 + NUM
g + PROPN
/ + SYM
dL + PROPN
, + PUNCT

 + SPACE
RDW + PROPN
15 + NUM
% + NOUN
, + PUNCT
neutrophils + VERB
65 + NUM
% + NOUN
, + PUNCT
and + CCONJ
lymphocytes + VERB
28 + NUM
% + NOUN
. + PUNCT

 + SPACE

In [15]:
for token in doc:
  print(token.text,"->", token.lemma_)

 ->

Patient -> Patient
CBC -> CBC
report -> report
shows -> show
hemoglobin -> hemoglobin
11.2 -> 11.2
g -> g
/ -> /
dL -> dL
, -> ,

 ->

hematocrit -> hematocrit
34 -> 34
% -> %
, -> ,
platelet -> platelet
count -> count
150000 -> 150000
per -> per
microliter -> microliter
, -> ,

 ->

MCV -> MCV
72 -> 72
fL -> fL
, -> ,
MCH -> MCH
24 -> 24
pg -> pg
, -> ,
MCHC -> MCHC
31 -> 31
g -> g
/ -> /
dL -> dL
, -> ,

 ->

RDW -> RDW
15 -> 15
% -> %
, -> ,
neutrophils -> neutrophil
65 -> 65
% -> %
, -> ,
and -> and
lymphocytes -> lymphocyte
28 -> 28
% -> %
. -> .

 ->

In [16]:
for ent in doc.ents:
  print(ent.text, "->", ent.label_)

CBC -> ORG
11.2 -> CARDINAL
34% -> PERCENT
150000 -> CARDINAL
MCV 72 -> ORG
24 -> DATE
MCHC -> ORG
31 -> CARDINAL
RDW -> ORG
15% -> PERCENT
65% -> PERCENT
28% -> PERCENT

In [14]:
knowledge_df = pd.read_excel(
    "Medical_Explanation_Knowledge_Base_Cleaned.xlsx"
)
knowledge_df.head()

,Parameter,Meaning,Simple Explanation,Units,Unit,Lower Range,Upper Range
0,HGB,Hemoglobin level,Protein in red blood cells that carries oxygen...,"g/dL, g/L",g/dL,12.0,16.0
1,HCT,Hematocrit level,Shows the percentage of blood made up of red b...,"%, L/L",%,36.0,46.0
2,PLT,Platelet count,"Shows the number of platelets, which help stop...","/µL, ×10⁹/L",/µL,150000.0,450000.0
3,MCV,Mean corpuscular volume,Shows the average size of red blood cells.,fL,fL,80.0,100.0
4,MCHC,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...,pg,g/dL,32.0,36.0

In [25]:
from google.colab import files

uploaded = files.upload()

Saving Medical_Explanation_Knowledge_Base_Cleaned.xlsx to Medical_Explanation_Knowledge_Base_Cleaned (1).xlsx

In [27]:
import pandas as pd

In [28]:
print(knowledge_df.columns.tolist())

['Parameter', 'Meaning', 'Simple Explanation', 'Units', 'Unit', 'Lower Range', 'Upper Range']

In [29]:
knowledge_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Parameter           9 non-null      str
 1   Meaning             9 non-null      str
 2   Simple Explanation  9 non-null      str
 3   Units               9 non-null      str
 4   Unit                9 non-null      str
 5   Lower Range         9 non-null      float64
 6   Upper Range         9 non-null      float64
dtypes: float64(2), str(5)
memory usage: 1.5 KB

In [30]:
knowledge_df.shape

(9, 7)

In [31]:
knowledge_df.isnull().sum()

Parameter             0
Meaning               0
Simple Explanation    0
Units                 0
Unit                  0
Lower Range           0
Upper Range           0
dtype: int64

In [32]:
import os

In [33]:
os.listdir()

['.config',
 'cbc_medexplain.csv',
 '.ipynb_checkpoints',
 'Medical explanation knowledge base.xlsx',
 'Medical_Explanation_Knowledge_Base_Cleaned (1).xlsx',
 'Medical_Explanation_Knowledge_Base_Cleaned.xlsx',
 'sample_data']

In [34]:
cbc_df.isnull().sum()

report_id          0
raw_report_text    0
overall_status     0
HGB_value          0
HGB_unit           0
HGB_ref_low        0
HGB_ref_high       0
HGB_status         0
HCT_value          0
HCT_unit           0
HCT_ref_low        0
HCT_ref_high       0
HCT_status         0
PLT_value          0
PLT_unit           0
PLT_ref_low        0
PLT_ref_high       0
PLT_status         0
MCV_value          0
MCV_unit           0
MCV_ref_low        0
MCV_ref_high       0
MCV_status         0
MCHC_value         0
MCHC_unit          0
MCHC_ref_low       0
MCHC_ref_high      0
MCHC_status        0
MCH_value          0
MCH_unit           0
MCH_ref_low        0
MCH_ref_high       0
MCH_status         0
RDW_value          0
RDW_unit           0
RDW_ref_low        0
RDW_ref_high       0
RDW_status         0
NE%_value          0
NE%_unit           0
NE%_ref_low        0
NE%_ref_high       0
NE%_status         0
LY%_value          0
LY%_unit           0
LY%_ref_low        0
LY%_ref_high       0
LY%_status         0
dtype: int64

In [35]:
knowledge_df.head(20)

,Parameter,Meaning,Simple Explanation,Units,Unit,Lower Range,Upper Range
0,HGB,Hemoglobin level,Protein in red blood cells that carries oxygen...,"g/dL, g/L",g/dL,12.0,16.0
1,HCT,Hematocrit level,Shows the percentage of blood made up of red b...,"%, L/L",%,36.0,46.0
2,PLT,Platelet count,"Shows the number of platelets, which help stop...","/µL, ×10⁹/L",/µL,150000.0,450000.0
3,MCV,Mean corpuscular volume,Shows the average size of red blood cells.,fL,fL,80.0,100.0
4,MCHC,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...,pg,g/dL,32.0,36.0
5,MCH,Mean corpuscular hemoglobin,Shows the average amount of hemoglobin in one ...,"g/dL, g/L",pg,27.0,33.0
6,RDW,Red cell distribution width,Shows how much red blood cells differ in size ...,%,%,11.5,14.5
7,NE%,Neutrophil percentage,Shows the percentage of white blood cells that...,%,%,40.0,70.0
8,LY%,Lymphocyte percentage,Shows the percentage of white blood cells that...,%,%,20.0,40.0

In [36]:
print(knowledge_df.columns.tolist())

['Parameter', 'Meaning', 'Simple Explanation', 'Units', 'Unit', 'Lower Range', 'Upper Range']

In [37]:
knowledge_df.to_string()

'  Parameter                                    Meaning                                                                                              Simple Explanation        Units  Unit  Lower Range  Upper Range\n0       HGB                           Hemoglobin level                                                 Protein in red blood cells that carries oxygen around the body.    g/dL, g/L  g/dL         12.0         16.0\n1       HCT                           Hematocrit level                                                       Shows the percentage of blood made up of red blood cells.       %, L/L     %         36.0         46.0\n2       PLT                             Platelet count                                       Shows the number of platelets, which help stop bleeding by forming clots.  /µL, ×10⁹/L   /µL     150000.0     450000.0\n3       MCV                    Mean corpuscular volume                                                                      Shows the average size of red blood cells.           fL    fL         80.0        100.0\n4      MCHC  Mean corpuscular hemoglobin concentration                                                    Shows how concentrated hemoglobin is inside red blood cells.           pg  g/dL         32.0         36.0\n5       MCH                Mean corpuscular hemoglobin                                                   Shows the average amount of hemoglobin in one red blood cell.    g/dL, g/L    pg         27.0         33.0\n6       RDW                Red cell distribution width                                                  Shows how much red blood cells differ in size from each other.            %     %         11.5         14.5\n7       NE%                      Neutrophil percentage                    Shows the percentage of white blood cells that are neutrophils, which help fight infections.            %     %         40.0         70.0\n8       LY%                      Lymphocyte percentage  Shows the percentage of white blood cells that are lymphocytes, which help the immune system fight infections.            %     %         20.0         40.0'

In [38]:
cbc_df.describe()

,HGB_value,HGB_ref_low,HGB_ref_high,HCT_value,HCT_ref_low,HCT_ref_high,PLT_value,PLT_ref_low,PLT_ref_high,MCV_value,...,MCH_ref_high,RDW_value,RDW_ref_low,RDW_ref_high,NE%_value,NE%_ref_low,NE%_ref_high,LY%_value,LY%_ref_low,LY%_ref_high
count,100.000000,100.0,100.0,100.000000,100.0,100.0,100.000000,100.0,100.0,100.000000,...,100.0,100.000000,100.0,100.0,100.000000,100.0,100.0,100.000000,100.0,100.0
mean,13.422000,12.0,16.0,39.762000,36.0,46.0,266870.000000,150000.0,450000.0,87.784000,...,33.0,13.666000,11.5,14.5,59.516000,40.0,70.0,27.923000,20.0,40.0
std,1.921993,0.0,0.0,5.651723,0.0,0.0,91483.580798,0.0,0.0,7.033796,...,0.0,1.653354,0.0,0.0,9.376854,0.0,0.0,7.015608,0.0,0.0
min,9.000000,12.0,16.0,28.100000,36.0,46.0,70000.000000,150000.0,450000.0,66.300000,...,33.0,11.600000,11.5,14.5,42.000000,40.0,70.0,10.400000,20.0,40.0
25%,12.450000,12.0,16.0,35.800000,36.0,46.0,220250.000000,150000.0,450000.0,84.750000,...,33.0,12.575000,11.5,14.5,53.700000,40.0,70.0,24.575000,20.0,40.0
50%,13.750000,12.0,16.0,40.700000,36.0,46.0,260500.000000,150000.0,450000.0,88.650000,...,33.0,13.100000,11.5,14.5,58.400000,40.0,70.0,28.750000,20.0,40.0
75%,14.500000,12.0,16.0,43.100000,36.0,46.0,293750.000000,150000.0,450000.0,92.275000,...,33.0,14.125000,11.5,14.5,63.175000,40.0,70.0,32.750000,20.0,40.0
max,17.400000,12.0,16.0,53.500000,36.0,46.0,646000.000000,150000.0,450000.0,99.000000,...,33.0,19.000000,11.5,14.5,83.900000,40.0,70.0,39.000000,20.0,40.0

In [39]:
cbc_df.head()

,report_id,raw_report_text,overall_status,HGB_value,HGB_unit,HGB_ref_low,HGB_ref_high,HGB_status,HCT_value,HCT_unit,...,NE%_value,NE%_unit,NE%_ref_low,NE%_ref_high,NE%_status,LY%_value,LY%_unit,LY%_ref_low,LY%_ref_high,LY%_status
0,CBC_001,COMPLETE BLOOD COUNT\n\nHemoglobin: 14.2 g/dL ...,Abnormal,14.2,g/dL,12.0,16.0,Normal,41.0,%,...,83.6,%,40.0,70.0,High,14.1,%,20.0,40.0,Low
1,CBC_002,COMPLETE BLOOD COUNT\n\nHb: 11.9 g/dL Referen...,Abnormal,11.9,g/dL,12.0,16.0,Low,35.5,%,...,59.4,%,40.0,70.0,Normal,31.1,%,20.0,40.0,Normal
2,CBC_003,COMPLETE BLOOD COUNT\n\nHGB: 11 g/dL Referenc...,Abnormal,11.0,g/dL,12.0,16.0,Low,30.1,%,...,60.1,%,40.0,70.0,Normal,37.9,%,20.0,40.0,Normal
3,CBC_004,COMPLETE BLOOD COUNT\n\nHemoglobin: 14.5 g/dL ...,Abnormal,14.5,g/dL,12.0,16.0,Normal,42.5,%,...,79.0,%,40.0,70.0,High,14.3,%,20.0,40.0,Low
4,CBC_005,COMPLETE BLOOD COUNT\n\nHb: 14.1 g/dL Referen...,Normal,14.1,g/dL,12.0,16.0,Normal,40.7,%,...,57.0,%,40.0,70.0,Normal,25.8,%,20.0,40.0,Normal

In [40]:
print(cbc_df.columns.tolist())

['report_id', 'raw_report_text', 'overall_status', 'HGB_value', 'HGB_unit', 'HGB_ref_low', 'HGB_ref_high', 'HGB_status', 'HCT_value', 'HCT_unit', 'HCT_ref_low', 'HCT_ref_high', 'HCT_status', 'PLT_value', 'PLT_unit', 'PLT_ref_low', 'PLT_ref_high', 'PLT_status', 'MCV_value', 'MCV_unit', 'MCV_ref_low', 'MCV_ref_high', 'MCV_status', 'MCHC_value', 'MCHC_unit', 'MCHC_ref_low', 'MCHC_ref_high', 'MCHC_status', 'MCH_value', 'MCH_unit', 'MCH_ref_low', 'MCH_ref_high', 'MCH_status', 'RDW_value', 'RDW_unit', 'RDW_ref_low', 'RDW_ref_high', 'RDW_status', 'NE%_value', 'NE%_unit', 'NE%_ref_low', 'NE%_ref_high', 'NE%_status', 'LY%_value', 'LY%_unit', 'LY%_ref_low', 'LY%_ref_high', 'LY%_status']

In [41]:
print(cbc_df.loc[0, "raw_report_text"])

COMPLETE BLOOD COUNT

Hemoglobin: 14.2 g/dL  Reference: 12-16 g/dL
Hematocrit: 41 %  Reference: 36-46 %
Platelet Count: 244,000 /µL  Reference: 150000-450000 /µL
MCV: 95.5 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.2 g/dL  Reference: 32-36 g/dL
MCH: 30.8 pg  Reference: 27-33 pg
RDW: 12.3 %  Reference: 11.5-14.5 %
Neutrophils: 83.6 %  Reference: 40-70 %
Lymphocytes: 14.1 %  Reference: 20-40 %

In [42]:
import spacy

nlp = spacy.load("en_core_web_sm")

print("Model loaded successfully")

Model loaded successfully

In [43]:
report_text = cbc_df.loc[0, "raw_report_text"]

doc = nlp(report_text)

print(doc.text)

COMPLETE BLOOD COUNT

Hemoglobin: 14.2 g/dL  Reference: 12-16 g/dL
Hematocrit: 41 %  Reference: 36-46 %
Platelet Count: 244,000 /µL  Reference: 150000-450000 /µL
MCV: 95.5 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.2 g/dL  Reference: 32-36 g/dL
MCH: 30.8 pg  Reference: 27-33 pg
RDW: 12.3 %  Reference: 11.5-14.5 %
Neutrophils: 83.6 %  Reference: 40-70 %
Lymphocytes: 14.1 %  Reference: 20-40 %

In [44]:
cbc_parameters = {
    "HGB": ["hemoglobin", "hb", "hgb"],
    "HCT": ["hematocrit", "hct"],
    "PLT": ["platelet", "platelets", "plt"],
    "MCV": ["mean corpuscular volume", "mcv"],
    "MCHC": ["mean corpuscular hemoglobin concentration", "mchc"],
    "MCH": ["mean corpuscular hemoglobin", "mch"],
    "RDW": ["red cell distribution width", "rdw"],
    "NE%": ["neutrophils", "neutrophil", "ne%"],
    "LY%": ["lymphocytes", "lymphocyte", "ly%"]
}
print(cbc_parameters)

{'HGB': ['hemoglobin', 'hb', 'hgb'], 'HCT': ['hematocrit', 'hct'], 'PLT': ['platelet', 'platelets', 'plt'], 'MCV': ['mean corpuscular volume', 'mcv'], 'MCHC': ['mean corpuscular hemoglobin concentration', 'mchc'], 'MCH': ['mean corpuscular hemoglobin', 'mch'], 'RDW': ['red cell distribution width', 'rdw'], 'NE%': ['neutrophils', 'neutrophil', 'ne%'], 'LY%': ['lymphocytes', 'lymphocyte', 'ly%']}

In [45]:
print(cbc_df.loc[0, "raw_report_text"])

COMPLETE BLOOD COUNT

Hemoglobin: 14.2 g/dL  Reference: 12-16 g/dL
Hematocrit: 41 %  Reference: 36-46 %
Platelet Count: 244,000 /µL  Reference: 150000-450000 /µL
MCV: 95.5 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.2 g/dL  Reference: 32-36 g/dL
MCH: 30.8 pg  Reference: 27-33 pg
RDW: 12.3 %  Reference: 11.5-14.5 %
Neutrophils: 83.6 %  Reference: 40-70 %
Lymphocytes: 14.1 %  Reference: 20-40 %

In [46]:
report_text = cbc_df.loc[0, "raw_report_text"]

doc = nlp(report_text)

print(doc.text)

COMPLETE BLOOD COUNT

Hemoglobin: 14.2 g/dL  Reference: 12-16 g/dL
Hematocrit: 41 %  Reference: 36-46 %
Platelet Count: 244,000 /µL  Reference: 150000-450000 /µL
MCV: 95.5 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.2 g/dL  Reference: 32-36 g/dL
MCH: 30.8 pg  Reference: 27-33 pg
RDW: 12.3 %  Reference: 11.5-14.5 %
Neutrophils: 83.6 %  Reference: 40-70 %
Lymphocytes: 14.1 %  Reference: 20-40 %

In [47]:
for ent in doc.ents:
    print(ent.text, "→", ent.label_)

14.2 → CARDINAL
12-16 → CARDINAL
41 % → PERCENT
36-46 % → PERCENT
244,000 → CARDINAL
150000-450000 → CARDINAL
MCV → ORG
95.5 → CARDINAL
80-100 → CARDINAL
33.2 → CARDINAL
32-36 → CARDINAL
30.8 → CARDINAL
27-33 → CARDINAL
RDW → ORG
12.3 % → PERCENT
11.5-14.5 % → PERCENT
83.6 % → PERCENT
40-70 % → PERCENT
14.1 % → PERCENT
20-40 % → PERCENT

In [48]:
report_lower=report_text.lower()

for parameter, variations in cbc_parameters.items():
  for variation in variations:
    if variation.lower() in report_lower:
      print(parameter, "->",variation)
      break

HGB -> hemoglobin
HCT -> hematocrit
PLT -> platelet
MCV -> mcv
MCHC -> mean corpuscular hemoglobin concentration
MCH -> mean corpuscular hemoglobin
RDW -> rdw
NE% -> neutrophils
LY% -> lymphocytes

In [49]:
import re

In [50]:
match = re.search(
    r"Hemoglobin:\s*([\d.]+)\s*(g/dL|g/L)",
    report_text,
    re.IGNORECASE
)

if match:
    print("Value:", match.group(1))
    print("Unit:", match.group(2))

Value: 14.2
Unit: g/dL

In [51]:
match = re.search(
    r"Hemoglobin:\s*[\d.]+\s*(?:g/dL|g/L)\s*Reference:\s*([\d.]+)-([\d.]+)",
    report_text,
    re.IGNORECASE
)

if match:
    print("Lower:", match.group(1))
    print("Upper:", match.group(2))

Lower: 12
Upper: 16

In [52]:
def determine_status(value, low, high):
    if value < low:
        return "Low"
    elif value > high:
        return "High"
    else:
        return "Normal"

In [53]:
value = 14.3
low=12
high=18
status= determine_status(value,low,high)
print(status)

Normal

In [ ]:
print(extracted_df)

In [16]:
parameters = [
    "HGB",
    "HCT",
    "PLT",
    "MCV",
    "MCHC",
    "MCH",
    "RDW",
    "NE%",
    "LY%"
]

for parameter in parameters:

    column = f"{parameter}_extracted"

    extracted_count = results_df[column].notna().sum()

    print(
        parameter,
        "→",
        extracted_count,
        "/",
        len(results_df)
    )

NameError: name 'results_df' is not defined

In [31]:
import re

def extract_cbc_report(report_text):

    results = {}

    patterns = {

        "HGB": r"(?:Hemoglobin|Hb|HGB)\s*:\s*([\d.]+)\s*(g/dL|g/L)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        "HCT": r"(?:Hematocrit|HCT|PCV)\s*:\s*([\d.]+)\s*(%|L/L)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        "PLT": r"(?:Platelet Count|Platelets|Platelet|PLT)\s*:\s*([\d,]+)\s*(/µL|×10⁹/L)\s*Reference\s*:\s*([\d,]+)\s*-\s*([\d,]+)",

        "MCV": r"(?:MCV|Mean Corpuscular Volume)\s*:\s*([\d.]+)\s*(fL)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        "MCHC": r"(?:Mean Corpuscular Hemoglobin Concentration|MCHC)\s*:\s*([\d.]+)\s*(g/dL|g/L)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        "MCH": r"(?:MCH|Mean Corpuscular Hemoglobin)\s*:\s*([\d.]+)\s*(pg)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        "RDW": r"(?:RDW|Red Cell Distribution Width)\s*:\s*([\d.]+)\s*(%)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        "NE%": r"(?:Neutrophils|Neutrophil\s*%|Neutrophil|NE%)\s*:\s*([\d.]+)\s*(%)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        "LY%": r"(?:Lymphocytes|Lymphocyte\s*%|Lymphocyte|LY%)\s*:\s*([\d.]+)\s*(%)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)"
    }

    for parameter, pattern in patterns.items():

        match = re.search(
            pattern,
            report_text,
            re.IGNORECASE
        )

        if match:

            value = float(match.group(1).replace(",", ""))
            unit = match.group(2)

            low = float(
                match.group(3).replace(",", "")
            )

            high = float(
                match.group(4).replace(",", "")
            )

            if value < low:
                status = "Low"

            elif value > high:
                status = "High"

            else:
                status = "Normal"

            results[parameter] = {
                "value": value,
                "unit": unit,
                "reference_low": low,
                "reference_high": high,
                "status": status
            }

    return results

In [64]:
report = cbc_df.loc[0, "raw_report_text"]

extracted = extract_cbc_report(report)

extracted_df = pd.DataFrame.from_dict(
    extracted,
    orient="index"
)

extracted_df

         value  unit  reference_low  reference_high  status
HGB       14.2  g/dL           12.0            16.0  Normal
HCT       41.0     %           36.0            46.0  Normal
PLT   244000.0   /µL       150000.0        450000.0  Normal
MCV       95.5    fL           80.0           100.0  Normal
MCHC      33.2  g/dL           32.0            36.0  Normal
MCH       30.8    pg           27.0            33.0  Normal
RDW       12.3     %           11.5            14.5  Normal
NE%       83.6     %           40.0            70.0    High
LY%       14.1     %           20.0            40.0     Low

In [17]:
all_results = []

for index, row in cbc_df.iterrows():

    extracted = extract_cbc_report(
        row["raw_report_text"]
    )

    result = {
        "report_id": row["report_id"]
    }

    for parameter, data in extracted.items():

        result[f"{parameter}_extracted"] = data["value"]

        result[f"{parameter}_status_extracted"] = data["status"]

    all_results.append(result)


results_df = pd.DataFrame(all_results)

In [66]:
parameters = [
    "HGB",
    "HCT",
    "PLT",
    "MCV",
    "MCHC",
    "MCH",
    "RDW",
    "NE%",
    "LY%"
]

for parameter in parameters:

    column = f"{parameter}_extracted"

    extracted_count = results_df[column].notna().sum()

    percentage = (
        extracted_count / len(results_df)
    ) * 100

    print(
        parameter,
        "→",
        extracted_count,
        "/",
        len(results_df),
        "|",
        round(percentage, 2),
        "%"
    )

HGB → 100 / 100 | 100.0 %
HCT → 67 / 100 | 67.0 %
PLT → 100 / 100 | 100.0 %
MCV → 100 / 100 | 100.0 %
MCHC → 100 / 100 | 100.0 %
MCH → 100 / 100 | 100.0 %
RDW → 100 / 100 | 100.0 %
NE% → 67 / 100 | 67.0 %
LY% → 67 / 100 | 67.0 %

In [67]:
parameters_to_check = ["HCT", "NE%", "LY%"]

for parameter in parameters_to_check:

    column = f"{parameter}_extracted"

    print("\n" + "=" * 60)
    print(parameter)
    print("=" * 60)

    failed = cbc_df[results_df[column].isna()]

    print("Failed reports:", len(failed))

    for _, row in failed.head(10).iterrows():
        print("\nReport ID:", row["report_id"])
        print(row["raw_report_text"])

============================================================
HCT
============================================================
Failed reports: 33

Report ID: CBC_002
COMPLETE BLOOD COUNT

Hb: 11.9 g/dL  Reference: 12-16 g/dL
PCV: 35.5 %  Reference: 36-46 %
Platelets: 278,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 86 fL  Reference: 80-100 fL
MCHC: 32.3 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 29.6 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.6 %  Reference: 11.5-14.5 %
Neutrophil %: 59.4 %  Reference: 40-70 %
Lymphocyte %: 31.1 %  Reference: 20-40 %

Report ID: CBC_005
COMPLETE BLOOD COUNT

Hb: 14.1 g/dL  Reference: 12-16 g/dL
PCV: 40.7 %  Reference: 36-46 %
Platelets: 242,000 /µL  Reference: 150000-450000 /µL
MCV: 85.9 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.4 g/dL  Reference: 32-36 g/dL
MCH: 31.4 pg  Reference: 27-33 pg
RDW: 13.1 %  Reference: 11.5-14.5 %
Neutrophil %: 57 %  Reference: 40-70 %
Lymphocyte %: 25.8 %  Reference: 20-40 %

Report ID: CBC_008
COMPLETE BLOOD COUNT

Hb: 11.2 g/dL  Reference: 12-16 g/dL
PCV: 31.4 %  Reference: 36-46 %
Platelets: 274,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 66.3 fL  Reference: 80-100 fL
MCHC: 33.6 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 24.5 pg  Reference: 27-33 pg
Red Cell Distribution Width: 16 %  Reference: 11.5-14.5 %
Neutrophil %: 65.8 %  Reference: 40-70 %
Lymphocyte %: 32.1 %  Reference: 20-40 %

Report ID: CBC_011
COMPLETE BLOOD COUNT

Hb: 13.7 g/dL  Reference: 12-16 g/dL
PCV: 39.6 %  Reference: 36-46 %
Platelets: 198,000 /µL  Reference: 150000-450000 /µL
MCV: 84.6 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.2 g/dL  Reference: 32-36 g/dL
MCH: 31.1 pg  Reference: 27-33 pg
RDW: 11.9 %  Reference: 11.5-14.5 %
Neutrophil %: 58.2 %  Reference: 40-70 %
Lymphocyte %: 28.6 %  Reference: 20-40 %

Report ID: CBC_014
COMPLETE BLOOD COUNT

Hb: 10.1 g/dL  Reference: 12-16 g/dL
PCV: 30.5 %  Reference: 36-46 %
Platelets: 256,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 75.4 fL  Reference: 80-100 fL
MCHC: 33.1 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 24.9 pg  Reference: 27-33 pg
Red Cell Distribution Width: 15.4 %  Reference: 11.5-14.5 %
Neutrophil %: 47.5 %  Reference: 40-70 %
Lymphocyte %: 23.7 %  Reference: 20-40 %

Report ID: CBC_017
COMPLETE BLOOD COUNT

Hb: 9.1 g/dL  Reference: 12-16 g/dL
PCV: 30.8 %  Reference: 36-46 %
Platelets: 265,000 /µL  Reference: 150000-450000 /µL
MCV: 85.4 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.8 g/dL  Reference: 32-36 g/dL
MCH: 29.3 pg  Reference: 27-33 pg
RDW: 16.4 %  Reference: 11.5-14.5 %
Neutrophil %: 67.4 %  Reference: 40-70 %
Lymphocyte %: 30.6 %  Reference: 20-40 %

Report ID: CBC_020
COMPLETE BLOOD COUNT

Hb: 17 g/dL  Reference: 12-16 g/dL
PCV: 49.3 %  Reference: 36-46 %
Platelets: 313,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 87.4 fL  Reference: 80-100 fL
MCHC: 33.5 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 27.6 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.7 %  Reference: 11.5-14.5 %
Neutrophil %: 65.8 %  Reference: 40-70 %
Lymphocyte %: 32.2 %  Reference: 20-40 %

Report ID: CBC_023
COMPLETE BLOOD COUNT

Hb: 15.5 g/dL  Reference: 12-16 g/dL
PCV: 46.4 %  Reference: 36-46 %
Platelets: 565,000 /µL  Reference: 150000-450000 /µL
MCV: 83.9 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.5 g/dL  Reference: 32-36 g/dL
MCH: 27.3 pg  Reference: 27-33 pg
RDW: 12.5 %  Reference: 11.5-14.5 %
Neutrophil %: 59.9 %  Reference: 40-70 %
Lymphocyte %: 36.8 %  Reference: 20-40 %

Report ID: CBC_026
COMPLETE BLOOD COUNT

Hb: 14.2 g/dL  Reference: 12-16 g/dL
PCV: 43.1 %  Reference: 36-46 %
Platelets: 207,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 88.4 fL  Reference: 80-100 fL
MCHC: 34.7 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 28.2 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.3 %  Reference: 11.5-14.5 %
Neutrophil %: 59.2 %  Reference: 40-70 %
Lymphocyte %: 35.2 %  Reference: 20-40 %

Report ID: CBC_029
COMPLETE BLOOD COUNT

Hb: 14.1 g/dL  Reference: 12-16 g/dL
PCV: 40 %  Reference: 36-46 %
Platelets: 138,000 /µL  Reference: 150000-450000 /µL
MCV: 89.3 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.1 g/dL  Reference: 32-36 g/dL
MCH: 30.3 pg  Reference: 27-33 pg
RDW: 13.6 %  Reference: 11.5-14.5 %
Neutrophil %: 58.8 %  Reference: 40-70 %
Lymphocyte %: 34.8 %  Reference: 20-40 %

============================================================
NE%
============================================================
Failed reports: 33

Report ID: CBC_002
COMPLETE BLOOD COUNT

Hb: 11.9 g/dL  Reference: 12-16 g/dL
PCV: 35.5 %  Reference: 36-46 %
Platelets: 278,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 86 fL  Reference: 80-100 fL
MCHC: 32.3 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 29.6 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.6 %  Reference: 11.5-14.5 %
Neutrophil %: 59.4 %  Reference: 40-70 %
Lymphocyte %: 31.1 %  Reference: 20-40 %

Report ID: CBC_005
COMPLETE BLOOD COUNT

Hb: 14.1 g/dL  Reference: 12-16 g/dL
PCV: 40.7 %  Reference: 36-46 %
Platelets: 242,000 /µL  Reference: 150000-450000 /µL
MCV: 85.9 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.4 g/dL  Reference: 32-36 g/dL
MCH: 31.4 pg  Reference: 27-33 pg
RDW: 13.1 %  Reference: 11.5-14.5 %
Neutrophil %: 57 %  Reference: 40-70 %
Lymphocyte %: 25.8 %  Reference: 20-40 %

Report ID: CBC_008
COMPLETE BLOOD COUNT

Hb: 11.2 g/dL  Reference: 12-16 g/dL
PCV: 31.4 %  Reference: 36-46 %
Platelets: 274,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 66.3 fL  Reference: 80-100 fL
MCHC: 33.6 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 24.5 pg  Reference: 27-33 pg
Red Cell Distribution Width: 16 %  Reference: 11.5-14.5 %
Neutrophil %: 65.8 %  Reference: 40-70 %
Lymphocyte %: 32.1 %  Reference: 20-40 %

Report ID: CBC_011
COMPLETE BLOOD COUNT

Hb: 13.7 g/dL  Reference: 12-16 g/dL
PCV: 39.6 %  Reference: 36-46 %
Platelets: 198,000 /µL  Reference: 150000-450000 /µL
MCV: 84.6 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.2 g/dL  Reference: 32-36 g/dL
MCH: 31.1 pg  Reference: 27-33 pg
RDW: 11.9 %  Reference: 11.5-14.5 %
Neutrophil %: 58.2 %  Reference: 40-70 %
Lymphocyte %: 28.6 %  Reference: 20-40 %

Report ID: CBC_014
COMPLETE BLOOD COUNT

Hb: 10.1 g/dL  Reference: 12-16 g/dL
PCV: 30.5 %  Reference: 36-46 %
Platelets: 256,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 75.4 fL  Reference: 80-100 fL
MCHC: 33.1 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 24.9 pg  Reference: 27-33 pg
Red Cell Distribution Width: 15.4 %  Reference: 11.5-14.5 %
Neutrophil %: 47.5 %  Reference: 40-70 %
Lymphocyte %: 23.7 %  Reference: 20-40 %

Report ID: CBC_017
COMPLETE BLOOD COUNT

Hb: 9.1 g/dL  Reference: 12-16 g/dL
PCV: 30.8 %  Reference: 36-46 %
Platelets: 265,000 /µL  Reference: 150000-450000 /µL
MCV: 85.4 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.8 g/dL  Reference: 32-36 g/dL
MCH: 29.3 pg  Reference: 27-33 pg
RDW: 16.4 %  Reference: 11.5-14.5 %
Neutrophil %: 67.4 %  Reference: 40-70 %
Lymphocyte %: 30.6 %  Reference: 20-40 %

Report ID: CBC_020
COMPLETE BLOOD COUNT

Hb: 17 g/dL  Reference: 12-16 g/dL
PCV: 49.3 %  Reference: 36-46 %
Platelets: 313,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 87.4 fL  Reference: 80-100 fL
MCHC: 33.5 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 27.6 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.7 %  Reference: 11.5-14.5 %
Neutrophil %: 65.8 %  Reference: 40-70 %
Lymphocyte %: 32.2 %  Reference: 20-40 %

Report ID: CBC_023
COMPLETE BLOOD COUNT

Hb: 15.5 g/dL  Reference: 12-16 g/dL
PCV: 46.4 %  Reference: 36-46 %
Platelets: 565,000 /µL  Reference: 150000-450000 /µL
MCV: 83.9 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.5 g/dL  Reference: 32-36 g/dL
MCH: 27.3 pg  Reference: 27-33 pg
RDW: 12.5 %  Reference: 11.5-14.5 %
Neutrophil %: 59.9 %  Reference: 40-70 %
Lymphocyte %: 36.8 %  Reference: 20-40 %

Report ID: CBC_026
COMPLETE BLOOD COUNT

Hb: 14.2 g/dL  Reference: 12-16 g/dL
PCV: 43.1 %  Reference: 36-46 %
Platelets: 207,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 88.4 fL  Reference: 80-100 fL
MCHC: 34.7 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 28.2 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.3 %  Reference: 11.5-14.5 %
Neutrophil %: 59.2 %  Reference: 40-70 %
Lymphocyte %: 35.2 %  Reference: 20-40 %

Report ID: CBC_029
COMPLETE BLOOD COUNT

Hb: 14.1 g/dL  Reference: 12-16 g/dL
PCV: 40 %  Reference: 36-46 %
Platelets: 138,000 /µL  Reference: 150000-450000 /µL
MCV: 89.3 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.1 g/dL  Reference: 32-36 g/dL
MCH: 30.3 pg  Reference: 27-33 pg
RDW: 13.6 %  Reference: 11.5-14.5 %
Neutrophil %: 58.8 %  Reference: 40-70 %
Lymphocyte %: 34.8 %  Reference: 20-40 %

============================================================
LY%
============================================================
Failed reports: 33

Report ID: CBC_002
COMPLETE BLOOD COUNT

Hb: 11.9 g/dL  Reference: 12-16 g/dL
PCV: 35.5 %  Reference: 36-46 %
Platelets: 278,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 86 fL  Reference: 80-100 fL
MCHC: 32.3 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 29.6 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.6 %  Reference: 11.5-14.5 %
Neutrophil %: 59.4 %  Reference: 40-70 %
Lymphocyte %: 31.1 %  Reference: 20-40 %

Report ID: CBC_005
COMPLETE BLOOD COUNT

Hb: 14.1 g/dL  Reference: 12-16 g/dL
PCV: 40.7 %  Reference: 36-46 %
Platelets: 242,000 /µL  Reference: 150000-450000 /µL
MCV: 85.9 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.4 g/dL  Reference: 32-36 g/dL
MCH: 31.4 pg  Reference: 27-33 pg
RDW: 13.1 %  Reference: 11.5-14.5 %
Neutrophil %: 57 %  Reference: 40-70 %
Lymphocyte %: 25.8 %  Reference: 20-40 %

Report ID: CBC_008
COMPLETE BLOOD COUNT

Hb: 11.2 g/dL  Reference: 12-16 g/dL
PCV: 31.4 %  Reference: 36-46 %
Platelets: 274,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 66.3 fL  Reference: 80-100 fL
MCHC: 33.6 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 24.5 pg  Reference: 27-33 pg
Red Cell Distribution Width: 16 %  Reference: 11.5-14.5 %
Neutrophil %: 65.8 %  Reference: 40-70 %
Lymphocyte %: 32.1 %  Reference: 20-40 %

Report ID: CBC_011
COMPLETE BLOOD COUNT

Hb: 13.7 g/dL  Reference: 12-16 g/dL
PCV: 39.6 %  Reference: 36-46 %
Platelets: 198,000 /µL  Reference: 150000-450000 /µL
MCV: 84.6 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.2 g/dL  Reference: 32-36 g/dL
MCH: 31.1 pg  Reference: 27-33 pg
RDW: 11.9 %  Reference: 11.5-14.5 %
Neutrophil %: 58.2 %  Reference: 40-70 %
Lymphocyte %: 28.6 %  Reference: 20-40 %

Report ID: CBC_014
COMPLETE BLOOD COUNT

Hb: 10.1 g/dL  Reference: 12-16 g/dL
PCV: 30.5 %  Reference: 36-46 %
Platelets: 256,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 75.4 fL  Reference: 80-100 fL
MCHC: 33.1 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 24.9 pg  Reference: 27-33 pg
Red Cell Distribution Width: 15.4 %  Reference: 11.5-14.5 %
Neutrophil %: 47.5 %  Reference: 40-70 %
Lymphocyte %: 23.7 %  Reference: 20-40 %

Report ID: CBC_017
COMPLETE BLOOD COUNT

Hb: 9.1 g/dL  Reference: 12-16 g/dL
PCV: 30.8 %  Reference: 36-46 %
Platelets: 265,000 /µL  Reference: 150000-450000 /µL
MCV: 85.4 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.8 g/dL  Reference: 32-36 g/dL
MCH: 29.3 pg  Reference: 27-33 pg
RDW: 16.4 %  Reference: 11.5-14.5 %
Neutrophil %: 67.4 %  Reference: 40-70 %
Lymphocyte %: 30.6 %  Reference: 20-40 %

Report ID: CBC_020
COMPLETE BLOOD COUNT

Hb: 17 g/dL  Reference: 12-16 g/dL
PCV: 49.3 %  Reference: 36-46 %
Platelets: 313,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 87.4 fL  Reference: 80-100 fL
MCHC: 33.5 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 27.6 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.7 %  Reference: 11.5-14.5 %
Neutrophil %: 65.8 %  Reference: 40-70 %
Lymphocyte %: 32.2 %  Reference: 20-40 %

Report ID: CBC_023
COMPLETE BLOOD COUNT

Hb: 15.5 g/dL  Reference: 12-16 g/dL
PCV: 46.4 %  Reference: 36-46 %
Platelets: 565,000 /µL  Reference: 150000-450000 /µL
MCV: 83.9 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.5 g/dL  Reference: 32-36 g/dL
MCH: 27.3 pg  Reference: 27-33 pg
RDW: 12.5 %  Reference: 11.5-14.5 %
Neutrophil %: 59.9 %  Reference: 40-70 %
Lymphocyte %: 36.8 %  Reference: 20-40 %

Report ID: CBC_026
COMPLETE BLOOD COUNT

Hb: 14.2 g/dL  Reference: 12-16 g/dL
PCV: 43.1 %  Reference: 36-46 %
Platelets: 207,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 88.4 fL  Reference: 80-100 fL
MCHC: 34.7 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 28.2 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.3 %  Reference: 11.5-14.5 %
Neutrophil %: 59.2 %  Reference: 40-70 %
Lymphocyte %: 35.2 %  Reference: 20-40 %

Report ID: CBC_029
COMPLETE BLOOD COUNT

Hb: 14.1 g/dL  Reference: 12-16 g/dL
PCV: 40 %  Reference: 36-46 %
Platelets: 138,000 /µL  Reference: 150000-450000 /µL
MCV: 89.3 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.1 g/dL  Reference: 32-36 g/dL
MCH: 30.3 pg  Reference: 27-33 pg
RDW: 13.6 %  Reference: 11.5-14.5 %
Neutrophil %: 58.8 %  Reference: 40-70 %
Lymphocyte %: 34.8 %  Reference: 20-40 %

In [68]:
import re

def extract_cbc_report(report_text):

    results = {}

    patterns = {

        # Hemoglobin
        "HGB": r"(?:Hemoglobin|Hb|HGB)\s*:\s*([\d.]+)\s*(g/dL|g/L)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        # Hematocrit / PCV
        "HCT": r"(?:Hematocrit|HCT|PCV)\s*:\s*([\d.]+)\s*(%|L/L)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        # Platelets
        "PLT": r"(?:Platelet Count|Platelets|Platelet|PLT)\s*:\s*([\d,]+)\s*(/µL|×10⁹/L)\s*Reference\s*:\s*([\d,]+)\s*-\s*([\d,]+)",

        # MCV
        "MCV": r"(?:MCV|Mean Corpuscular Volume)\s*:\s*([\d.]+)\s*(fL)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        # MCHC
        "MCHC": r"(?:Mean Corpuscular Hemoglobin Concentration|MCHC)\s*:\s*([\d.]+)\s*(g/dL|g/L)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        # MCH
        "MCH": r"(?:MCH|Mean Corpuscular Hemoglobin)\s*:\s*([\d.]+)\s*(pg)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        # RDW
        "RDW": r"(?:RDW|Red Cell Distribution Width)\s*:\s*([\d.]+)\s*(%)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        # Neutrophils
        "NE%": r"(?:Neutrophils|Neutrophil\s*%|Neutrophil|NE%)\s*:\s*([\d.]+)\s*(%)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",

        # Lymphocytes
        "LY%": r"(?:Lymphocytes|Lymphocyte\s*%|Lymphocyte|LY%)\s*:\s*([\d.]+)\s*(%)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)"
    }

    for parameter, pattern in patterns.items():

        match = re.search(
            pattern,
            report_text,
            re.IGNORECASE
        )

        if match:

            value = float(
                match.group(1).replace(",", "")
            )

            unit = match.group(2)

            low = float(
                match.group(3).replace(",", "")
            )

            high = float(
                match.group(4).replace(",", "")
            )

            # Determine status
            if value < low:
                status = "Low"

            elif value > high:
                status = "High"

            else:
                status = "Normal"

            results[parameter] = {
                "value": value,
                "unit": unit,
                "reference_low": low,
                "reference_high": high,
                "status": status
            }

    return results

In [69]:
report = cbc_df.loc[
    cbc_df["report_id"] == "CBC_002",
    "raw_report_text"
].iloc[0]

extracted = extract_cbc_report(report)

pd.DataFrame.from_dict(
    extracted,
    orient="index"
)

         value  unit  reference_low  reference_high  status
HGB       11.9  g/dL           12.0            16.0     Low
HCT       35.5     %           36.0            46.0     Low
PLT   278000.0   /µL       150000.0        450000.0  Normal
MCV       86.0    fL           80.0           100.0  Normal
MCHC      32.3  g/dL           32.0            36.0  Normal
MCH       29.6    pg           27.0            33.0  Normal
RDW       12.6     %           11.5            14.5  Normal
NE%       59.4     %           40.0            70.0  Normal
LY%       31.1     %           20.0            40.0  Normal

In [70]:
all_results = []

for index, row in cbc_df.iterrows():

    extracted = extract_cbc_report(
        row["raw_report_text"]
    )

    result = {
        "report_id": row["report_id"]
    }

    for parameter, data in extracted.items():

        result[f"{parameter}_extracted"] = data["value"]

        result[f"{parameter}_status_extracted"] = data["status"]

    all_results.append(result)


results_df = pd.DataFrame(all_results)

In [71]:
parameters = [
    "HGB",
    "HCT",
    "PLT",
    "MCV",
    "MCHC",
    "MCH",
    "RDW",
    "NE%",
    "LY%"
]

for parameter in parameters:

    column = f"{parameter}_extracted"

    extracted_count = results_df[column].notna().sum()

    percentage = (
        extracted_count / len(results_df)
    ) * 100

    print(
        parameter,
        "→",
        extracted_count,
        "/",
        len(results_df),
        "|",
        round(percentage, 2),
        "%"
    )

HGB → 100 / 100 | 100.0 %
HCT → 100 / 100 | 100.0 %
PLT → 100 / 100 | 100.0 %
MCV → 100 / 100 | 100.0 %
MCHC → 100 / 100 | 100.0 %
MCH → 100 / 100 | 100.0 %
RDW → 100 / 100 | 100.0 %
NE% → 100 / 100 | 100.0 %
LY% → 100 / 100 | 100.0 %

In [72]:
parameters = [
    "HGB",
    "HCT",
    "PLT",
    "MCV",
    "MCHC",
    "MCH",
    "RDW",
    "NE%",
    "LY%"
]

for parameter in parameters:

    extracted_col = f"{parameter}_extracted"
    dataset_col = f"{parameter}_value"

    matches = (
        results_df[extracted_col].round(2)
        ==
        cbc_df[dataset_col].round(2)
    )

    accuracy = matches.mean() * 100

    print(
        parameter,
        "Value Accuracy:",
        round(accuracy, 2),
        "%"
    )

HGB Value Accuracy: 100.0 %
HCT Value Accuracy: 100.0 %
PLT Value Accuracy: 100.0 %
MCV Value Accuracy: 100.0 %
MCHC Value Accuracy: 100.0 %
MCH Value Accuracy: 100.0 %
RDW Value Accuracy: 100.0 %
NE% Value Accuracy: 100.0 %
LY% Value Accuracy: 100.0 %

In [73]:
for parameter in parameters:

    extracted_col = f"{parameter}_status_extracted"
    dataset_col = f"{parameter}_status"

    matches = (
        results_df[extracted_col]
        ==
        cbc_df[dataset_col]
    )

    accuracy = matches.mean() * 100

    print(
        parameter,
        "Status Accuracy:",
        round(accuracy, 2),
        "%"
    )

HGB Status Accuracy: 100.0 %
HCT Status Accuracy: 100.0 %
PLT Status Accuracy: 100.0 %
MCV Status Accuracy: 100.0 %
MCHC Status Accuracy: 100.0 %
MCH Status Accuracy: 100.0 %
RDW Status Accuracy: 100.0 %
NE% Status Accuracy: 100.0 %
LY% Status Accuracy: 100.0 %

In [74]:
knowledge_df

,Parameter,Meaning,Simple Explanation,Units,Unit,Lower Range,Upper Range
0,HGB,Hemoglobin level,Protein in red blood cells that carries oxygen...,"g/dL, g/L",g/dL,12.0,16.0
1,HCT,Hematocrit level,Shows the percentage of blood made up of red b...,"%, L/L",%,36.0,46.0
2,PLT,Platelet count,"Shows the number of platelets, which help stop...","/µL, ×10⁹/L",/µL,150000.0,450000.0
3,MCV,Mean corpuscular volume,Shows the average size of red blood cells.,fL,fL,80.0,100.0
4,MCHC,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...,pg,g/dL,32.0,36.0
5,MCH,Mean corpuscular hemoglobin,Shows the average amount of hemoglobin in one ...,"g/dL, g/L",pg,27.0,33.0
6,RDW,Red cell distribution width,Shows how much red blood cells differ in size ...,%,%,11.5,14.5
7,NE%,Neutrophil percentage,Shows the percentage of white blood cells that...,%,%,40.0,70.0
8,LY%,Lymphocyte percentage,Shows the percentage of white blood cells that...,%,%,20.0,40.0

In [75]:
print(knowledge_df.columns.tolist())

['Parameter', 'Meaning', 'Simple Explanation', 'Units', 'Unit', 'Lower Range', 'Upper Range']

In [18]:
knowledge_base = {}

for _, row in knowledge_df.iterrows():
    parameter = row["Parameter"]
    knowledge_base[parameter] = {
        "Meaning": row["Meaning"],
        "Simple Explanation": row["Simple Explanation"],
        "Unit": row["Unit"]
    }

KeyError: 'parameter'

In [77]:
knowledge_base

{}

In [19]:
knowledge_base["HGB: "]

KeyError: 'HGB: '

In [12]:
knowledge_df=knowledge_df.rename(columns={
    "parameter": "Parameter",
    "meaning": "Meaning",
    "simple explanation": "Simple Explanation",
    "Units": "Units",
    "Lower range":"Lower Range"
})

NameError: name 'knowledge_df' is not defined

In [ ]:
knowledge_df["Parameter"] = (
    knowledge_df["Parameter"]
    .astype(str)
    .str.strip()
    .str.rstrip(":")
    .str.strip()
)

In [ ]:
knowledge_df["Parameter"].tolist()

In [ ]:
standard_units = {
    "HGB": "g/dL",
    "HCT": "%",
    "PLT": "/µL",
    "MCV": "fL",
    "MCHC": "g/dL",
    "MCH": "pg",
    "RDW": "%",
    "NE%": "%",
    "LY%": "%"
}

knowledge_df["Unit"] = knowledge_df["Parameter"].map(standard_units)

In [81]:
range_data = []

for parameter in parameters:

    low = cbc_df[f"{parameter}_ref_low"].iloc[0]
    high = cbc_df[f"{parameter}_ref_high"].iloc[0]

    range_data.append({
        "Parameter": parameter,
        "Lower Range": low,
        "Upper Range": high
    })

range_df = pd.DataFrame(range_data)

range_df

  Parameter  Lower Range  Upper Range
0       HGB         12.0         16.0
1       HCT         36.0         46.0
2       PLT     150000.0     450000.0
3       MCV         80.0        100.0
4      MCHC         32.0         36.0
5       MCH         27.0         33.0
6       RDW         11.5         14.5
7       NE%         40.0         70.0
8       LY%         20.0         40.0

In [82]:
knowledge_df= knowledge_df.drop(columns=["Lower Range"],
                                errors="ignore")
knowledge_df = knowledge_df.merge(
    range_df,
    on="Parameter",
    how="left"
)

In [83]:
knowledge_df

,Parameter,Meaning,Simple Explanation,Units,Unit,Upper Range_x,Lower Range,Upper Range_y
0,HGB,Hemoglobin level,Protein in red blood cells that carries oxygen...,"g/dL, g/L",g/dL,16.0,12.0,16.0
1,HCT,Hematocrit level,Shows the percentage of blood made up of red b...,"%, L/L",%,46.0,36.0,46.0
2,PLT,Platelet count,"Shows the number of platelets, which help stop...","/µL, ×10⁹/L",/µL,450000.0,150000.0,450000.0
3,MCV,Mean corpuscular volume,Shows the average size of red blood cells.,fL,fL,100.0,80.0,100.0
4,MCHC,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...,pg,g/dL,36.0,32.0,36.0
5,MCH,Mean corpuscular hemoglobin,Shows the average amount of hemoglobin in one ...,"g/dL, g/L",pg,33.0,27.0,33.0
6,RDW,Red cell distribution width,Shows how much red blood cells differ in size ...,%,%,14.5,11.5,14.5
7,NE%,Neutrophil percentage,Shows the percentage of white blood cells that...,%,%,70.0,40.0,70.0
8,LY%,Lymphocyte percentage,Shows the percentage of white blood cells that...,%,%,40.0,20.0,40.0

In [84]:
knowledge_df.to_excel(
    "Medical_Explanation_Knowledge_Base_Cleaned.xlsx",
    index=False
)

In [85]:
knowledge_df

,Parameter,Meaning,Simple Explanation,Units,Unit,Upper Range_x,Lower Range,Upper Range_y
0,HGB,Hemoglobin level,Protein in red blood cells that carries oxygen...,"g/dL, g/L",g/dL,16.0,12.0,16.0
1,HCT,Hematocrit level,Shows the percentage of blood made up of red b...,"%, L/L",%,46.0,36.0,46.0
2,PLT,Platelet count,"Shows the number of platelets, which help stop...","/µL, ×10⁹/L",/µL,450000.0,150000.0,450000.0
3,MCV,Mean corpuscular volume,Shows the average size of red blood cells.,fL,fL,100.0,80.0,100.0
4,MCHC,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...,pg,g/dL,36.0,32.0,36.0
5,MCH,Mean corpuscular hemoglobin,Shows the average amount of hemoglobin in one ...,"g/dL, g/L",pg,33.0,27.0,33.0
6,RDW,Red cell distribution width,Shows how much red blood cells differ in size ...,%,%,14.5,11.5,14.5
7,NE%,Neutrophil percentage,Shows the percentage of white blood cells that...,%,%,70.0,40.0,70.0
8,LY%,Lymphocyte percentage,Shows the percentage of white blood cells that...,%,%,40.0,20.0,40.0

In [86]:
from google.colab import files

files.download("cbc_medexplain.csv")

In [ ]:
files.download("Medical_Explanation_Knowledge_Base_Cleaned.xlsx")

PHASE 4 — Knowledge Base **Integration**

In [ ]:
knowledge_base = (
    knowledge_df
    .set_index("Parameter")
    .to_dict(orient="index")
)

print(knowledge_base["HGB"])
print(knowledge_base["NE%"])

In [87]:
print("CBC Dataset:", cbc_df.shape)
print("Knowledge Base:", knowledge_df.shape)
print("Parameters:", parameters)

CBC Dataset: (100, 48)
Knowledge Base: (9, 8)
Parameters: ['HGB', 'HCT', 'PLT', 'MCV', 'MCHC', 'MCH', 'RDW', 'NE%', 'LY%']

In [90]:
print(knowledge_df.columns.tolist())
print(knowledge_df["Parameter"].tolist())

['Parameter', 'Meaning', 'Simple Explanation', 'Units', 'Unit', 'Upper Range_x', 'Lower Range', 'Upper Range_y']
['HGB', 'HCT', 'PLT', 'MCV', 'MCHC', 'MCH', 'RDW', 'NE%', 'LY%']

In [93]:
knowledge_base =(
    knowledge_df
    .set_index("Parameter")
    .to_dict(orient="index")
)
print(knowledge_base["HGB"])
print(knowledge_base["NE%"])

{'Meaning': 'Hemoglobin level', 'Simple Explanation': 'Protein in red blood cells that carries oxygen around the body.', 'Units': 'g/dL, g/L', 'Unit': 'g/dL', 'Upper Range_x': 16.0, 'Lower Range': 12.0, 'Upper Range_y': 16.0}
{'Meaning': ' Neutrophil percentage', 'Simple Explanation': 'Shows the percentage of white blood cells that are neutrophils, which help fight infections.', 'Units': '%', 'Unit': '%', 'Upper Range_x': 70.0, 'Lower Range': 40.0, 'Upper Range_y': 70.0}

In [8]:
def generate_explanation(parameter, result):
    info = knowledge_base.get(parameter)

    if info is None:
        return "Knowledge not available."

    return {
        "Parameter": parameter,
        "Value": result["value"],
        "Unit": result["unit"],
        "Reference Range": (
            f'{result["reference_low"]} - '
            f'{result["reference_high"]}'
        ),
        "Status": result["status"],
        "Meaning": info["Meaning"],
        "Simple Explanation": info["Simple Explanation"]
    }

In [95]:
sample_report = cbc_df.iloc[0]["raw_report_text"]

extracted_results = extract_cbc_report(sample_report)

hgb_result = generate_explanation(
    "HGB",
    extracted_results["HGB"]
)

print(hgb_result)

{'Parameter': 'HGB', 'Value': 14.2, 'Unit': 'g/dL', 'Reference Range': '12.0 - 16.0', 'Status': 'Normal', 'Meaning': 'Hemoglobin level', 'Simple Explanation': 'Protein in red blood cells that carries oxygen around the body.'}

In [96]:
all_explanations = []

for parameter, result in extracted_results.items():
    explanation = generate_explanation(parameter, result)
    all_explanations.append(explanation)

explanations_df = pd.DataFrame(all_explanations)

display(explanations_df)

,Parameter,Value,Unit,Reference Range,Status,Meaning,Simple Explanation
0,HGB,14.2,g/dL,12.0 - 16.0,Normal,Hemoglobin level,Protein in red blood cells that carries oxygen...
1,HCT,41.0,%,36.0 - 46.0,Normal,Hematocrit level,Shows the percentage of blood made up of red b...
2,PLT,244000.0,/µL,150000.0 - 450000.0,Normal,Platelet count,"Shows the number of platelets, which help stop..."
3,MCV,95.5,fL,80.0 - 100.0,Normal,Mean corpuscular volume,Shows the average size of red blood cells.
4,MCHC,33.2,g/dL,32.0 - 36.0,Normal,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...
5,MCH,30.8,pg,27.0 - 33.0,Normal,Mean corpuscular hemoglobin,Shows the average amount of hemoglobin in one ...
6,RDW,12.3,%,11.5 - 14.5,Normal,Red cell distribution width,Shows how much red blood cells differ in size ...
7,NE%,83.6,%,40.0 - 70.0,High,Neutrophil percentage,Shows the percentage of white blood cells that...
8,LY%,14.1,%,20.0 - 40.0,Low,Lymphocyte percentage,Shows the percentage of white blood cells that...

In [33]:
all_report_explanations = []

for _, row in cbc_df.iterrows():

    report_id = row["report_id"]
    report_text = row["raw_report_text"]

    extracted_results = extract_cbc_report(report_text)

    for parameter, result in extracted_results.items():

        explanation = generate_explanation(
            parameter,
            result
        )

        # Skip missing Knowledge Base entries
        if not isinstance(explanation, dict):
            print(
                f"Warning: Explanation unavailable for "
                f"{parameter} in {report_id}"
            )
            continue

        explanation["Report ID"] = report_id

        all_report_explanations.append(explanation)

all_explanations_df = pd.DataFrame(all_report_explanations)

print("Total explanations:", len(all_explanations_df))
print("Unique reports:", all_explanations_df["Report ID"].nunique())

display(all_explanations_df.head(10))

Total explanations: 900
Unique reports: 100

,Parameter,Value,Unit,Reference Range,Status,Meaning,Simple Explanation,Report ID
0,HGB,14.2,g/dL,12.0 - 16.0,Normal,Hemoglobin level,Protein in red blood cells that carries oxygen...,CBC_001
1,HCT,41.0,%,36.0 - 46.0,Normal,Hematocrit level,Shows the percentage of blood made up of red b...,CBC_001
2,PLT,244000.0,/µL,150000.0 - 450000.0,Normal,Platelet count,"Shows the number of platelets, which help stop...",CBC_001
3,MCV,95.5,fL,80.0 - 100.0,Normal,Mean corpuscular volume,Shows the average size of red blood cells.,CBC_001
4,MCHC,33.2,g/dL,32.0 - 36.0,Normal,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...,CBC_001
5,MCH,30.8,pg,27.0 - 33.0,Normal,Mean corpuscular hemoglobin,Shows the average amount of hemoglobin in one ...,CBC_001
6,RDW,12.3,%,11.5 - 14.5,Normal,Red cell distribution width,Shows how much red blood cells differ in size ...,CBC_001
7,NE%,83.6,%,40.0 - 70.0,High,Neutrophil percentage,Shows the percentage of white blood cells that...,CBC_001
8,LY%,14.1,%,20.0 - 40.0,Low,Lymphocyte percentage,Shows the percentage of white blood cells that...,CBC_001
9,HGB,11.9,g/dL,12.0 - 16.0,Low,Hemoglobin level,Protein in red blood cells that carries oxygen...,CBC_002

In [24]:
expected_parameters =set(parameters)

missing_results=[]
for report_id in cbc_df["report_id"]:
    report_results =all_explanations_df[
        all_explanations_df["Report ID"]==report_id
    ]
    extracted_parameters=set(report_results["Parameter"])
    missing_parameters = expected_parameters - extracted_parameters

    for parameter in missing_parameters:
      missing_results.append({
          "Report ID": report_id,
          "Missing Parameter":parameter
      })
missing_df = pd.DataFrame(missing_results)
print("Total missing parameter results:",len(missing_df))
display(missing_df.head(20))

Total missing parameter results: 99

   Report ID Missing Parameter
0    CBC_002               HCT
1    CBC_002               NE%
2    CBC_002               LY%
3    CBC_005               HCT
4    CBC_005               NE%
5    CBC_005               LY%
6    CBC_008               HCT
7    CBC_008               NE%
8    CBC_008               LY%
9    CBC_011               HCT
10   CBC_011               NE%
11   CBC_011               LY%
12   CBC_014               HCT
13   CBC_014               NE%
14   CBC_014               LY%
15   CBC_017               HCT
16   CBC_017               NE%
17   CBC_017               LY%
18   CBC_020               HCT
19   CBC_020               NE%

In [26]:
print(
    missing_df["Missing Parameter"]
    .value_counts()
)

Missing Parameter
HCT    33
NE%    33
LY%    33
Name: count, dtype: int64

In [27]:
problem_reports = cbc_df[
    cbc_df["report_id"].isin(
        missing_df["Report ID"].unique()
    )
]

for _, row in problem_reports.head(3).iterrows():

    print("=" * 80)
    print(row["report_id"])
    print(row["raw_report_text"])
    print()

================================================================================
CBC_002
COMPLETE BLOOD COUNT

Hb: 11.9 g/dL  Reference: 12-16 g/dL
PCV: 35.5 %  Reference: 36-46 %
Platelets: 278,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 86 fL  Reference: 80-100 fL
MCHC: 32.3 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 29.6 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.6 %  Reference: 11.5-14.5 %
Neutrophil %: 59.4 %  Reference: 40-70 %
Lymphocyte %: 31.1 %  Reference: 20-40 %

================================================================================
CBC_005
COMPLETE BLOOD COUNT

Hb: 14.1 g/dL  Reference: 12-16 g/dL
PCV: 40.7 %  Reference: 36-46 %
Platelets: 242,000 /µL  Reference: 150000-450000 /µL
MCV: 85.9 fL  Reference: 80-100 fL
Mean Corpuscular Hemoglobin Concentration: 33.4 g/dL  Reference: 32-36 g/dL
MCH: 31.4 pg  Reference: 27-33 pg
RDW: 13.1 %  Reference: 11.5-14.5 %
Neutrophil %: 57 %  Reference: 40-70 %
Lymphocyte %: 25.8 %  Reference: 20-40 %

================================================================================
CBC_008
COMPLETE BLOOD COUNT

Hb: 11.2 g/dL  Reference: 12-16 g/dL
PCV: 31.4 %  Reference: 36-46 %
Platelets: 274,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 66.3 fL  Reference: 80-100 fL
MCHC: 33.6 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 24.5 pg  Reference: 27-33 pg
Red Cell Distribution Width: 16 %  Reference: 11.5-14.5 %
Neutrophil %: 65.8 %  Reference: 40-70 %
Lymphocyte %: 32.1 %  Reference: 20-40 %

In [28]:
test_text = cbc_df[
    cbc_df["report_id"] == "CBC_002"
]["raw_report_text"].iloc[0]

print(test_text)

print("\nHCT match:")
print(re.search(
    r"(?:Hematocrit|HCT|PCV)\s*:\s*([\d.]+)\s*(%|L/L)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",
    test_text,
    re.IGNORECASE
))

print("\nNE% match:")
print(re.search(
    r"(?:Neutrophils|Neutrophil\s*%|Neutrophil|NE%)\s*:\s*([\d.]+)\s*(%)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",
    test_text,
    re.IGNORECASE
))

print("\nLY% match:")
print(re.search(
    r"(?:Lymphocytes|Lymphocyte\s*%|Lymphocyte|LY%)\s*:\s*([\d.]+)\s*(%)\s*Reference\s*:\s*([\d.]+)\s*-\s*([\d.]+)",
    test_text,
    re.IGNORECASE
))

COMPLETE BLOOD COUNT

Hb: 11.9 g/dL  Reference: 12-16 g/dL
PCV: 35.5 %  Reference: 36-46 %
Platelets: 278,000 /µL  Reference: 150000-450000 /µL
Mean Corpuscular Volume: 86 fL  Reference: 80-100 fL
MCHC: 32.3 g/dL  Reference: 32-36 g/dL
Mean Corpuscular Hemoglobin: 29.6 pg  Reference: 27-33 pg
Red Cell Distribution Width: 12.6 %  Reference: 11.5-14.5 %
Neutrophil %: 59.4 %  Reference: 40-70 %
Lymphocyte %: 31.1 %  Reference: 20-40 %

HCT match:
<re.Match object; span=(59, 88), match='PCV: 35.5 %  Reference: 36-46'>

NE% match:
<re.Match object; span=(354, 392), match='Neutrophil %: 59.4 %  Reference: 40-70'>

LY% match:
<re.Match object; span=(395, 433), match='Lymphocyte %: 31.1 %  Reference: 20-40'>

In [29]:
test_results = extract_cbc_report(test_text)

print(test_results.keys())
print()

for parameter in ["HCT", "NE%", "LY%"]:
    print(parameter, ":", test_results.get(parameter))

dict_keys(['HGB', 'PLT', 'MCV', 'MCHC', 'MCH', 'RDW'])

HCT : None
NE% : None
LY% : None

In [30]:
for parameter in ["HCT", "NE%", "LY%"]:
    print("\n", parameter)
    print(knowledge_base.get(parameter))

 HCT
{'Meaning': 'Hematocrit level', 'Simple Explanation': 'Shows the percentage of blood made up of red blood cells.', 'Units': '%, L/L', 'Unit': '%', 'Lower Range': 36.0, 'Upper Range': 46.0}

 NE%
{'Meaning': ' Neutrophil percentage', 'Simple Explanation': 'Shows the percentage of white blood cells that are neutrophils, which help fight infections.', 'Units': '%', 'Unit': '%', 'Lower Range': 40.0, 'Upper Range': 70.0}

 LY%
{'Meaning': 'Lymphocyte percentage', 'Simple Explanation': 'Shows the percentage of white blood cells that are lymphocytes, which help the immune system fight infections.', 'Units': '%', 'Unit': '%', 'Lower Range': 20.0, 'Upper Range': 40.0}

In [32]:
test_results = extract_cbc_report(test_text)

print(test_results.keys())

for parameter in parameters:
    print(parameter, ":", test_results.get(parameter))

dict_keys(['HGB', 'HCT', 'PLT', 'MCV', 'MCHC', 'MCH', 'RDW', 'NE%', 'LY%'])
HGB : {'value': 11.9, 'unit': 'g/dL', 'reference_low': 12.0, 'reference_high': 16.0, 'status': 'Low'}
HCT : {'value': 35.5, 'unit': '%', 'reference_low': 36.0, 'reference_high': 46.0, 'status': 'Low'}
PLT : {'value': 278000.0, 'unit': '/µL', 'reference_low': 150000.0, 'reference_high': 450000.0, 'status': 'Normal'}
MCV : {'value': 86.0, 'unit': 'fL', 'reference_low': 80.0, 'reference_high': 100.0, 'status': 'Normal'}
MCHC : {'value': 32.3, 'unit': 'g/dL', 'reference_low': 32.0, 'reference_high': 36.0, 'status': 'Normal'}
MCH : {'value': 29.6, 'unit': 'pg', 'reference_low': 27.0, 'reference_high': 33.0, 'status': 'Normal'}
RDW : {'value': 12.6, 'unit': '%', 'reference_low': 11.5, 'reference_high': 14.5, 'status': 'Normal'}
NE% : {'value': 59.4, 'unit': '%', 'reference_low': 40.0, 'reference_high': 70.0, 'status': 'Normal'}
LY% : {'value': 31.1, 'unit': '%', 'reference_low': 20.0, 'reference_high': 40.0, 'status': 'Normal'}

In [35]:
all_report_explanations = []

for _, row in cbc_df.iterrows():

    report_id = row["report_id"]
    report_text = row["raw_report_text"]

    extracted_results = extract_cbc_report(report_text)

    for parameter, result in extracted_results.items():

        explanation = generate_explanation(
            parameter,
            result
        )

        if not isinstance(explanation, dict):
            continue

        explanation["Report ID"] = report_id

        all_report_explanations.append(explanation)

all_explanations_df = pd.DataFrame(
    all_report_explanations
)

print("Total explanations:", len(all_explanations_df))
print(
    "Unique reports:",
    all_explanations_df["Report ID"].nunique()
)

Total explanations: 900
Unique reports: 100

PHASE 5 — STRUCTURED MEDICAL **`INTERPRETATION`**

Phase 4.1 : including the suggestion box in interpretation

In [43]:
suggestion_knowledge_base = {

    "HGB": {
        "Low": (
            "Maintain a balanced diet containing iron-rich foods such as "
            "leafy green vegetables, beans and fortified foods. Include "
            "vitamin C-rich foods to support iron absorption. If the low "
            "level persists, discuss it with a healthcare professional."
        ),
        "Normal": (
            "Maintain a balanced diet containing adequate iron, folate "
            "and vitamin B12, and continue routine health monitoring."
        ),
        "High": (
            "Maintain good hydration and a balanced lifestyle. If the "
            "elevated level persists, discuss the result with a healthcare professional."
        )
    },

    "HCT": {
        "Low": (
            "Maintain a balanced diet and adequate nutritional intake. "
            "If the value remains low, discuss the result with a healthcare professional."
        ),
        "Normal": (
            "Maintain a balanced diet, adequate hydration and regular health monitoring."
        ),
        "High": (
            "Maintain adequate hydration and discuss a persistently high "
            "value with a healthcare professional."
        )
    },

    "PLT": {
        "Low": (
            "Avoid self-medication and discuss a persistently low platelet "
            "count with a healthcare professional. Follow medical advice "
            "regarding medications and activities."
        ),
        "Normal": (
            "Maintain balanced nutrition and continue routine health monitoring."
        ),
        "High": (
            "Maintain a balanced lifestyle and discuss a persistently high "
            "platelet count with a healthcare professional."
        )
    },

    "MCV": {
        "Low": (
            "Maintain a balanced diet containing iron, folate and vitamin B12. "
            "If the value remains low, discuss possible nutritional causes "
            "with a healthcare professional."
        ),
        "Normal": (
            "Maintain a balanced diet and continue routine health monitoring."
        ),
        "High": (
            "Maintain a balanced diet containing adequate vitamin B12 and folate. "
            "If the value remains high, discuss the result with a healthcare professional."
        )
    },

    "MCHC": {
        "Low": (
            "Maintain a balanced diet with adequate iron and other essential "
            "nutrients. If the value remains low, discuss the result with "
            "a healthcare professional."
        ),
        "Normal": (
            "Maintain balanced nutrition and continue routine health monitoring."
        ),
        "High": (
            "Maintain a balanced diet and discuss a persistently elevated "
            "value with a healthcare professional."
        )
    },

    "MCH": {
        "Low": (
            "Maintain a balanced diet containing adequate iron and other "
            "essential nutrients. Persistent abnormalities should be discussed "
            "with a healthcare professional."
        ),
        "Normal": (
            "Maintain balanced nutrition and continue routine health monitoring."
        ),
        "High": (
            "Maintain a balanced diet containing adequate vitamin B12 and folate. "
            "Discuss persistent abnormalities with a healthcare professional."
        )
    },

    "RDW": {
        "Low": (
            "A slightly low RDW generally does not require a specific dietary "
            "measure by itself. Maintain a balanced diet and discuss persistent "
            "abnormalities with a healthcare professional."
        ),
        "Normal": (
            "Maintain a balanced diet and continue routine health monitoring."
        ),
        "High": (
            "Maintain a balanced diet containing iron, folate and vitamin B12. "
            "If the value remains elevated, discuss the result with a healthcare professional."
        )
    },

    "NE%": {
        "Low": (
            "Maintain a balanced diet and good general health practices. "
            "If the value remains low or symptoms are present, discuss the "
            "result with a healthcare professional."
        ),
        "Normal": (
            "Maintain a balanced diet and continue routine health monitoring."
        ),
        "High": (
            "Interpret the result together with the rest of the CBC and clinical "
            "context. If the elevation persists or symptoms are present, discuss "
            "the result with a healthcare professional."
        )
    },

    "LY%": {
        "Low": (
            "Maintain a balanced diet and healthy lifestyle. Interpret the result "
            "together with the rest of the CBC. Persistent abnormalities should "
            "be discussed with a healthcare professional."
        ),
        "Normal": (
            "Maintain a balanced diet and continue routine health monitoring."
        ),
        "High": (
            "Maintain a balanced diet and healthy lifestyle. If the elevation "
            "persists or symptoms are present, discuss the result with a "
            "healthcare professional."
        )
    }
}

In [54]:
def generate_structured_interpretation(parameter, result):

    # Clean parameter and status
    parameter = str(parameter).strip().upper()
    status = str(result["status"]).strip().title()

    # Get knowledge base information
    info = knowledge_base.get(parameter)

    if info is None:
        return {
            "Parameter": parameter,
            "Value": result["value"],
            "Unit": result["unit"],
            "Reference Range": (
                f'{result["reference_low"]} - '
                f'{result["reference_high"]}'
            ),
            "Status": status,
            "Meaning": "Knowledge not available.",
            "Simple Explanation": "Knowledge not available.",
            "Interpretation": "Knowledge not available.",
            "Suggestions": "Please discuss the result with a healthcare professional."
        }

    value = result["value"]
    unit = result["unit"]
    low = result["reference_low"]
    high = result["reference_high"]

    meaning = info["Meaning"]
    explanation = info["Simple Explanation"]

    reference_range = f"{low} - {high}"

    # -----------------------------
    # MEDICAL INTERPRETATION
    # -----------------------------

    if status == "Normal":

        interpretation = (
            f"{meaning} is within the provided reference range "
            f"({reference_range} {unit}). "
            f"{explanation}"
        )

    elif status == "Low":

        interpretation = (
            f"{meaning} is below the provided reference range "
            f"({reference_range} {unit}). "
            f"{explanation} "
            f"A low value may be associated with certain health conditions, "
            f"but clinical interpretation requires additional information."
        )

    elif status == "High":

        interpretation = (
            f"{meaning} is above the provided reference range "
            f"({reference_range} {unit}). "
            f"{explanation} "
            f"A high value may be associated with certain health conditions, "
            f"but clinical interpretation requires additional information."
        )

    else:

        interpretation = (
            "The status of this parameter could not be determined."
        )

    # -----------------------------
    # PARAMETER-SPECIFIC SUGGESTION
    # -----------------------------

    parameter_suggestions = suggestion_knowledge_base.get(
        parameter,
        {}
    )

    suggestions = parameter_suggestions.get(
        status,
        "Maintain a balanced lifestyle and discuss abnormal results with a healthcare professional."
    )

    # -----------------------------
    # FINAL STRUCTURED RESULT
    # -----------------------------

    return {
        "Parameter": parameter,
        "Value": value,
        "Unit": unit,
        "Reference Range": reference_range,
        "Status": status,
        "Meaning": meaning,
        "Simple Explanation": explanation,
        "Interpretation": interpretation,
        "Suggestions": suggestions
    }

In [ ]:
test_results = extract_cbc_report(
    cbc_df.iloc[1]["raw_report_text"]
)
test_interpretation = generate_structured_interpretation(
    "HGB",
    test_results["HGB"]
)
test_interpretation

In [55]:
report_text = cbc_df.iloc[1]["raw_report_text"]

extracted = extract_cbc_report(report_text)

structured_results = []

for parameter, result in extracted.items():

    interpretation = generate_structured_interpretation(
        parameter,
        result
    )

    structured_results.append(interpretation)

structured_df = pd.DataFrame(structured_results)

In [56]:
structured_df.columns.tolist()

['Parameter',
 'Value',
 'Unit',
 'Reference Range',
 'Status',
 'Meaning',
 'Simple Explanation',
 'Interpretation',
 'Suggestions']

In [57]:
structured_df[
    [
        "Parameter",
        "Status",
        "Suggestions"
    ]
]

  Parameter  Status                                        Suggestions
0       HGB     Low  Maintain a balanced diet containing iron-rich ...
1       HCT     Low  Maintain a balanced diet and adequate nutritio...
2       PLT  Normal  Maintain balanced nutrition and continue routi...
3       MCV  Normal  Maintain a balanced diet and continue routine ...
4      MCHC  Normal  Maintain balanced nutrition and continue routi...
5       MCH  Normal  Maintain balanced nutrition and continue routi...
6       RDW  Normal  Maintain a balanced diet and continue routine ...
7       NE%  Normal  Maintain a balanced diet and continue routine ...
8       LY%  Normal  Maintain a balanced diet and continue routine ...

5.1: continue step 5

In [59]:
all_structured_results = []

for _, row in cbc_df.iterrows():

    report_id = row["report_id"]
    report_text = row["raw_report_text"]

    extracted = extract_cbc_report(report_text)

    for parameter, result in extracted.items():

        interpretation = generate_structured_interpretation(
            parameter,
            result
        )

        interpretation["Report ID"] = report_id

        all_structured_results.append(
            interpretation
        )

all_structured_df = pd.DataFrame(all_structured_results)

In [60]:
print("Total structured results:", len(all_structured_df))

Total structured results: 900

In [61]:
print(
    "Unique reports:",
    all_structured_df["Report ID"].nunique()
)

print(
    "Unique parameters:",
    all_structured_df["Parameter"].nunique()
)

Unique reports: 100
Unique parameters: 9

In [63]:
print(
    "Missing suggestions:",
    all_structured_df["Suggestions"].isna().sum()
)

Missing suggestions: 0

In [64]:
print(
    "Missing suggestions:",
    all_structured_df["Suggestions"].isna().sum()
)

Missing suggestions: 0

In [65]:
all_structured_df["Status"].value_counts()

Status
Normal    732
Low       104
High       64
Name: count, dtype: int64

In [66]:
all_structured_df.head(10)

,Parameter,Value,Unit,Reference Range,Status,Meaning,Simple Explanation,Interpretation,Suggestions,Report ID
0,HGB,14.2,g/dL,12.0 - 16.0,Normal,Hemoglobin level,Protein in red blood cells that carries oxygen...,Hemoglobin level is within the provided refere...,Maintain a balanced diet containing adequate i...,CBC_001
1,HCT,41.0,%,36.0 - 46.0,Normal,Hematocrit level,Shows the percentage of blood made up of red b...,Hematocrit level is within the provided refere...,"Maintain a balanced diet, adequate hydration a...",CBC_001
2,PLT,244000.0,/µL,150000.0 - 450000.0,Normal,Platelet count,"Shows the number of platelets, which help stop...",Platelet count is within the provided referenc...,Maintain balanced nutrition and continue routi...,CBC_001
3,MCV,95.5,fL,80.0 - 100.0,Normal,Mean corpuscular volume,Shows the average size of red blood cells.,Mean corpuscular volume is within the provided...,Maintain a balanced diet and continue routine ...,CBC_001
4,MCHC,33.2,g/dL,32.0 - 36.0,Normal,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...,Mean corpuscular hemoglobin concentration is w...,Maintain balanced nutrition and continue routi...,CBC_001
5,MCH,30.8,pg,27.0 - 33.0,Normal,Mean corpuscular hemoglobin,Shows the average amount of hemoglobin in one ...,Mean corpuscular hemoglobin is within the prov...,Maintain balanced nutrition and continue routi...,CBC_001
6,RDW,12.3,%,11.5 - 14.5,Normal,Red cell distribution width,Shows how much red blood cells differ in size ...,Red cell distribution width is within the prov...,Maintain a balanced diet and continue routine ...,CBC_001
7,NE%,83.6,%,40.0 - 70.0,High,Neutrophil percentage,Shows the percentage of white blood cells that...,Neutrophil percentage is above the provided r...,Interpret the result together with the rest of...,CBC_001
8,LY%,14.1,%,20.0 - 40.0,Low,Lymphocyte percentage,Shows the percentage of white blood cells that...,Lymphocyte percentage is below the provided re...,Maintain a balanced diet and healthy lifestyle...,CBC_001
9,HGB,11.9,g/dL,12.0 - 16.0,Low,Hemoglobin level,Protein in red blood cells that carries oxygen...,Hemoglobin level is below the provided referen...,Maintain a balanced diet containing iron-rich ...,CBC_002

                 CBC REPORT
                      ↓
              NLP PROCESSING
                      ↓
           PARAMETER EXTRACTION
                      ↓
       ┌──────────────┼──────────────┐
       ↓              ↓              ↓
     Value           Unit      Reference Range
       └──────────────┼──────────────┘
                      ↓
             STATUS CLASSIFICATION
              ↙       ↓       ↘
            LOW     NORMAL     HIGH
              \       |       /
               \      |      /
                KNOWLEDGE BASE
                      ↓
              INTERPRETATION
                      ↓
                SUGGESTIONS
                      ↓
            STRUCTURED RESULTS
                      ↓
                900 RECORDS

In [67]:
report_001 = all_structured_df[
    all_structured_df["Report ID"] == "CBC_001"
]

report_001

,Parameter,Value,Unit,Reference Range,Status,Meaning,Simple Explanation,Interpretation,Suggestions,Report ID
0,HGB,14.2,g/dL,12.0 - 16.0,Normal,Hemoglobin level,Protein in red blood cells that carries oxygen...,Hemoglobin level is within the provided refere...,Maintain a balanced diet containing adequate i...,CBC_001
1,HCT,41.0,%,36.0 - 46.0,Normal,Hematocrit level,Shows the percentage of blood made up of red b...,Hematocrit level is within the provided refere...,"Maintain a balanced diet, adequate hydration a...",CBC_001
2,PLT,244000.0,/µL,150000.0 - 450000.0,Normal,Platelet count,"Shows the number of platelets, which help stop...",Platelet count is within the provided referenc...,Maintain balanced nutrition and continue routi...,CBC_001
3,MCV,95.5,fL,80.0 - 100.0,Normal,Mean corpuscular volume,Shows the average size of red blood cells.,Mean corpuscular volume is within the provided...,Maintain a balanced diet and continue routine ...,CBC_001
4,MCHC,33.2,g/dL,32.0 - 36.0,Normal,Mean corpuscular hemoglobin concentration,Shows how concentrated hemoglobin is inside re...,Mean corpuscular hemoglobin concentration is w...,Maintain balanced nutrition and continue routi...,CBC_001
5,MCH,30.8,pg,27.0 - 33.0,Normal,Mean corpuscular hemoglobin,Shows the average amount of hemoglobin in one ...,Mean corpuscular hemoglobin is within the prov...,Maintain balanced nutrition and continue routi...,CBC_001
6,RDW,12.3,%,11.5 - 14.5,Normal,Red cell distribution width,Shows how much red blood cells differ in size ...,Red cell distribution width is within the prov...,Maintain a balanced diet and continue routine ...,CBC_001
7,NE%,83.6,%,40.0 - 70.0,High,Neutrophil percentage,Shows the percentage of white blood cells that...,Neutrophil percentage is above the provided r...,Interpret the result together with the rest of...,CBC_001
8,LY%,14.1,%,20.0 - 40.0,Low,Lymphocyte percentage,Shows the percentage of white blood cells that...,Lymphocyte percentage is below the provided re...,Maintain a balanced diet and healthy lifestyle...,CBC_001

In [68]:
abnormal_001 = report_001[
    report_001["Status"] != "Normal"
]

abnormal_001[
    [
        "Parameter",
        "Value",
        "Unit",
        "Reference Range",
        "Status"
    ]
]

  Parameter  Value Unit Reference Range Status
7       NE%   83.6    %     40.0 - 70.0   High
8       LY%   14.1    %     20.0 - 40.0    Low

In [69]:
def create_patient_summary(report_df):

    report_id = report_df["Report ID"].iloc[0]

    normal_parameters = report_df[
        report_df["Status"] == "Normal"
    ]["Parameter"].tolist()

    low_parameters = report_df[
        report_df["Status"] == "Low"
    ]["Parameter"].tolist()

    high_parameters = report_df[
        report_df["Status"] == "High"
    ]["Parameter"].tolist()

    interpretations = report_df[
        "Interpretation"
    ].tolist()

    suggestions = report_df[
        "Suggestions"
    ].tolist()

    return {
        "Report ID": report_id,
        "Normal Parameters": normal_parameters,
        "Low Parameters": low_parameters,
        "High Parameters": high_parameters,
        "Interpretations": interpretations,
        "Suggestions": suggestions
    }

In [70]:
summary_001 = create_patient_summary(report_001)

summary_001

{'Report ID': 'CBC_001',
 'Normal Parameters': ['HGB', 'HCT', 'PLT', 'MCV', 'MCHC', 'MCH', 'RDW'],
 'Low Parameters': ['LY%'],
 'High Parameters': ['NE%'],
 'Interpretations': ['Hemoglobin level is within the provided reference range (12.0 - 16.0 g/dL). Protein in red blood cells that carries oxygen around the body.',
  'Hematocrit level is within the provided reference range (36.0 - 46.0 %). Shows the percentage of blood made up of red blood cells.',
  'Platelet count is within the provided reference range (150000.0 - 450000.0 /µL). Shows the number of platelets, which help stop bleeding by forming clots.',
  'Mean corpuscular volume is within the provided reference range (80.0 - 100.0 fL). Shows the average size of red blood cells.',
  'Mean corpuscular hemoglobin concentration is within the provided reference range (32.0 - 36.0 g/dL). Shows how concentrated hemoglobin is inside red blood cells.',
  'Mean corpuscular hemoglobin is within the provided reference range (27.0 - 33.0 pg). Shows the average amount of hemoglobin in one red blood cell.',
  'Red cell distribution width is within the provided reference range (11.5 - 14.5 %). Shows how much red blood cells differ in size from each other.',
  ' Neutrophil percentage is above the provided reference range (40.0 - 70.0 %). Shows the percentage of white blood cells that are neutrophils, which help fight infections. A high value may be associated with certain health conditions, but clinical interpretation requires additional information.',
  'Lymphocyte percentage is below the provided reference range (20.0 - 40.0 %). Shows the percentage of white blood cells that are lymphocytes, which help the immune system fight infections. A low value may be associated with certain health conditions, but clinical interpretation requires additional information.'],
 'Suggestions': ['Maintain a balanced diet containing adequate iron, folate and vitamin B12, and continue routine health monitoring.',
  'Maintain a balanced diet, adequate hydration and regular health monitoring.',
  'Maintain balanced nutrition and continue routine health monitoring.',
  'Maintain a balanced diet and continue routine health monitoring.',
  'Maintain balanced nutrition and continue routine health monitoring.',
  'Maintain balanced nutrition and continue routine health monitoring.',
  'Maintain a balanced diet and continue routine health monitoring.',
  'Interpret the result together with the rest of the CBC and clinical context. If the elevation persists or symptoms are present, discuss the result with a healthcare professional.',
  'Maintain a balanced diet and healthy lifestyle. Interpret the result together with the rest of the CBC. Persistent abnormalities should be discussed with a healthcare professional.']}

In [71]:
patient_summaries = []

for report_id, report_group in all_structured_df.groupby("Report ID"):

    summary = create_patient_summary(report_group)

    patient_summaries.append(summary)

patient_summary_df = pd.DataFrame(patient_summaries)

In [72]:
print("Total patient summaries:", len(patient_summary_df))

Total patient summaries: 100

In [73]:
patient_summary_df.columns.tolist()

['Report ID',
 'Normal Parameters',
 'Low Parameters',
 'High Parameters',
 'Interpretations',
 'Suggestions']

In [74]:
patient_summary_df.iloc[0]

Report ID                                                      CBC_001
Normal Parameters                 [HGB, HCT, PLT, MCV, MCHC, MCH, RDW]
Low Parameters                                                   [LY%]
High Parameters                                                  [NE%]
Interpretations      [Hemoglobin level is within the provided refer...
Suggestions          [Maintain a balanced diet containing adequate ...
Name: 0, dtype: object

before adding genAI essence to it  , first make the interpretations shoart and understandable

In [75]:
def create_compact_cbc_summary(report_df):

    report_id = report_df["Report ID"].iloc[0]

    lines = []

    for _, row in report_df.iterrows():

        line = (
            f'{row["Parameter"]}: '
            f'{row["Value"]} '
            f'{row["Unit"]} — '
            f'{row["Status"]}'
        )

        lines.append(line)

    summary = (
        f"CBC Report: {report_id}\n\n"
        + "\n".join(lines)
    )

    return summary

In [76]:
report_001 = all_structured_df[
    all_structured_df["Report ID"] == "CBC_001"
]

compact_summary_001 = create_compact_cbc_summary(
    report_001
)

print(compact_summary_001)

CBC Report: CBC_001

HGB: 14.2 g/dL — Normal
HCT: 41.0 % — Normal
PLT: 244000.0 /µL — Normal
MCV: 95.5 fL — Normal
MCHC: 33.2 g/dL — Normal
MCH: 30.8 pg — Normal
RDW: 12.3 % — Normal
NE%: 83.6 % — High
LY%: 14.1 % — Low

In [77]:
compact_summaries = []

for report_id, report_group in all_structured_df.groupby("Report ID"):

    compact_summary = create_compact_cbc_summary(
        report_group
    )

    compact_summaries.append({
        "Report ID": report_id,
        "CBC Summary": compact_summary
    })

compact_summary_df = pd.DataFrame(
    compact_summaries
)

In [78]:
compact_summary_df.head()

  Report ID                                        CBC Summary
0   CBC_001  CBC Report: CBC_001\n\nHGB: 14.2 g/dL — Normal...
1   CBC_002  CBC Report: CBC_002\n\nHGB: 11.9 g/dL — Low\nH...
2   CBC_003  CBC Report: CBC_003\n\nHGB: 11.0 g/dL — Low\nH...
3   CBC_004  CBC Report: CBC_004\n\nHGB: 14.5 g/dL — Normal...
4   CBC_005  CBC Report: CBC_005\n\nHGB: 14.1 g/dL — Normal...

In [79]:
print(
    compact_summary_df.iloc[50]["CBC Summary"]
)

CBC Report: CBC_051

HGB: 14.1 g/dL — Normal
HCT: 39.9 % — Normal
PLT: 290000.0 /µL — Normal
MCV: 85.0 fL — Normal
MCHC: 32.5 g/dL — Normal
MCH: 30.8 pg — Normal
RDW: 13.2 % — Normal
NE%: 54.3 % — Normal
LY%: 38.3 % — Normal

In [86]:
print(
    compact_summary_df.iloc[5]["CBC Summary"]
)

CBC Report: CBC_006

HGB: 12.0 g/dL — Normal
HCT: 34.8 % — Low
PLT: 561000.0 /µL — High
MCV: 97.8 fL — Normal
MCHC: 33.6 g/dL — Normal
MCH: 31.3 pg — Normal
RDW: 12.6 % — Normal
NE%: 50.9 % — Normal
LY%: 26.2 % — Normal

In [87]:
def generate_overall_cbc_summary(report_df):

    normal_params = report_df[
        report_df["Status"] == "Normal"
    ]["Parameter"].tolist()

    low_params = report_df[
        report_df["Status"] == "Low"
    ]["Parameter"].tolist()

    high_params = report_df[
        report_df["Status"] == "High"
    ]["Parameter"].tolist()

    total_parameters = len(report_df)
    normal_count = len(normal_params)
    low_count = len(low_params)
    high_count = len(high_params)

    # --------------------------------
    # Build overall summary
    # --------------------------------

    parts = []

    if normal_count == total_parameters:

        parts.append(
            "All measured CBC parameters are within the provided "
            "reference ranges."
        )

    else:

        if normal_count > 0:

            parts.append(
                f"{normal_count} of {total_parameters} measured CBC "
                f"parameters are within the provided reference ranges."
            )

        if low_count > 0:

            low_text = ", ".join(low_params)

            parts.append(
                f"The following parameter(s) are below the provided "
                f"reference ranges: {low_text}."
            )

        if high_count > 0:

            high_text = ", ".join(high_params)

            parts.append(
                f"The following parameter(s) are above the provided "
                f"reference ranges: {high_text}."
            )

        parts.append(
            "These findings should be interpreted together with the "
            "rest of the CBC, symptoms, medical history and other "
            "clinical information."
        )

    overall_summary = " ".join(parts)

    return overall_summary

In [88]:
report_001 = all_structured_df[
    all_structured_df["Report ID"] == "CBC_001"
]

overall_summary_001 = generate_overall_cbc_summary(
    report_001
)

print(overall_summary_001)

7 of 9 measured CBC parameters are within the provided reference ranges. The following parameter(s) are below the provided reference ranges: LY%. The following parameter(s) are above the provided reference ranges: NE%. These findings should be interpreted together with the rest of the CBC, symptoms, medical history and other clinical information.

In [90]:
overall_summaries = []

for report_id, report_group in all_structured_df.groupby("Report ID"):

    overall_summary = generate_overall_cbc_summary(
        report_group
    )

    overall_summaries.append({
        "Report ID": report_id,
        "Overall CBC Summary": overall_summary
    })

overall_summary_df = pd.DataFrame(
    overall_summaries
)

In [91]:
print(
    "Total overall summaries:",
    len(overall_summary_df)
)

Total overall summaries: 100

In [92]:
overall_summary_df.head(5)

  Report ID                                Overall CBC Summary
0   CBC_001  7 of 9 measured CBC parameters are within the ...
1   CBC_002  7 of 9 measured CBC parameters are within the ...
2   CBC_003  4 of 9 measured CBC parameters are within the ...
3   CBC_004  6 of 9 measured CBC parameters are within the ...
4   CBC_005  All measured CBC parameters are within the pro...

In [93]:
final_report_df = compact_summary_df.merge(
    overall_summary_df,
    on="Report ID",
    how="left"
)

final_report_df.head()

,Report ID,CBC Summary,Overall CBC Summary
0,CBC_001,CBC Report: CBC_001\n\nHGB: 14.2 g/dL — Normal...,7 of 9 measured CBC parameters are within the ...
1,CBC_002,CBC Report: CBC_002\n\nHGB: 11.9 g/dL — Low\nH...,7 of 9 measured CBC parameters are within the ...
2,CBC_003,CBC Report: CBC_003\n\nHGB: 11.0 g/dL — Low\nH...,4 of 9 measured CBC parameters are within the ...
3,CBC_004,CBC Report: CBC_004\n\nHGB: 14.5 g/dL — Normal...,6 of 9 measured CBC parameters are within the ...
4,CBC_005,CBC Report: CBC_005\n\nHGB: 14.1 g/dL — Normal...,All measured CBC parameters are within the pro...

In [94]:
final_report_df.columns.tolist()

['Report ID', 'CBC Summary', 'Overall CBC Summary']

                    RAW CBC REPORT
                          ↓
                     spaCy NLP
                          ↓
                Information Extraction
                          ↓
              ┌───────────┴───────────┐
              ↓                       ↓
        Parameter Data          Reference Range
              ↓                       ↓
              └───────────┬───────────┘
                          ↓
                  Status Classification
                          ↓
                    Knowledge Base
                          ↓
              Interpretation + Suggestions
                          ↓
                  900 structured rows
                          ↓
             ┌────────────┴────────────┐
             ↓                         ↓
      Compact CBC Summary       Overall CBC Summary
             └────────────┬────────────┘
                          ↓
                  FINAL REPORT DATA
                          ↓
                    GENERATIVE AI
                          ↓
             Patient-Friendly Explanation

Related Findings Detection

In [95]:
def detect_related_findings(report_df):

    findings = []

    # Convert parameter-status information into a dictionary
    status = dict(
        zip(
            report_df["Parameter"],
            report_df["Status"]
        )
    )

    # --------------------------------------------------
    # 1. Low HGB + Low HCT
    # --------------------------------------------------
    if status.get("HGB") == "Low" and status.get("HCT") == "Low":

        findings.append(
            "HGB and HCT are both below the provided reference ranges. "
            "This combination may indicate a reduced red-cell related "
            "finding and should be interpreted with clinical context."
        )

    # --------------------------------------------------
    # 2. Low HGB + Low MCV
    # --------------------------------------------------
    if status.get("HGB") == "Low" and status.get("MCV") == "Low":

        findings.append(
            "Low HGB together with low MCV may indicate a microcytic "
            "pattern. Further clinical evaluation may be required."
        )

    # --------------------------------------------------
    # 3. Low HGB + Low MCH
    # --------------------------------------------------
    if status.get("HGB") == "Low" and status.get("MCH") == "Low":

        findings.append(
            "Low HGB together with low MCH may indicate reduced "
            "hemoglobin content in red blood cells. Clinical context "
            "is required for interpretation."
        )

    # --------------------------------------------------
    # 4. Low HGB + Low MCHC
    # --------------------------------------------------
    if status.get("HGB") == "Low" and status.get("MCHC") == "Low":

        findings.append(
            "Low HGB together with low MCHC may indicate a "
            "hypochromic pattern. This finding requires clinical context."
        )

    # --------------------------------------------------
    # 5. High MCV + High MCH
    # --------------------------------------------------
    if status.get("MCV") == "High" and status.get("MCH") == "High":

        findings.append(
            "High MCV together with high MCH may indicate a macrocytic "
            "pattern. Further clinical evaluation may be required."
        )

    # --------------------------------------------------
    # 6. High RDW + Low HGB
    # --------------------------------------------------
    if status.get("RDW") == "High" and status.get("HGB") == "Low":

        findings.append(
            "High RDW together with low HGB indicates variation in "
            "red blood cell size alongside low hemoglobin. Clinical "
            "evaluation may be required."
        )

    # --------------------------------------------------
    # 7. High NE% + Low LY%
    # --------------------------------------------------
    if status.get("NE%") == "High" and status.get("LY%") == "Low":

        findings.append(
            "NE% is high while LY% is low. This relative differential "
            "pattern should be interpreted together with the complete "
            "CBC and clinical context."
        )

    # --------------------------------------------------
    # 8. Low NE% + High LY%
    # --------------------------------------------------
    if status.get("NE%") == "Low" and status.get("LY%") == "High":

        findings.append(
            "NE% is low while LY% is high. This relative differential "
            "pattern should be interpreted together with the complete "
            "CBC and clinical context."
        )

    # --------------------------------------------------
    # If no relationship is detected
    # --------------------------------------------------
    if len(findings) == 0:

        findings.append(
            "No significant parameter relationship was identified "
            "from the available CBC parameters."
        )

    return findings

In [96]:
cbc001_df = all_structured_df[
    all_structured_df["Report ID"] == "CBC_001"
]

related_findings_001 = detect_related_findings(cbc001_df)

for i, finding in enumerate(related_findings_001, 1):

    print(f"{i}. {finding}")

1. NE% is high while LY% is low. This relative differential pattern should be interpreted together with the complete CBC and clinical context.

In [97]:
related_findings_all = []

for report_id, report_group in all_structured_df.groupby("Report ID"):

    findings = detect_related_findings(report_group)

    related_findings_all.append({
        "Report ID": report_id,
        "Related Findings": findings
    })

related_findings_df = pd.DataFrame(
    related_findings_all
)

In [98]:
print("Total reports:", len(related_findings_df))
print("Unique reports:", related_findings_df["Report ID"].nunique())

Total reports: 100
Unique reports: 100

In [99]:
related_findings_df["Related Findings Text"] = (
    related_findings_df["Related Findings"]
    .apply(lambda x: "\n".join(f"• {item}" for item in x))
)

related_findings_df[
    ["Report ID", "Related Findings Text"]
].head()

  Report ID                              Related Findings Text
0   CBC_001  • NE% is high while LY% is low. This relative ...
1   CBC_002  • HGB and HCT are both below the provided refe...
2   CBC_003  • HGB and HCT are both below the provided refe...
3   CBC_004  • NE% is high while LY% is low. This relative ...
4   CBC_005  • No significant parameter relationship was id...

In [100]:
def generate_final_cbc_report(report_df):

    # -----------------------------------------
    # 1. Generate individual parameter results
    # -----------------------------------------
    structured_results = []

    for _, row in report_df.iterrows():

        report_id = row["report_id"]
        report_text = row["raw_report_text"]

        extracted = extract_cbc_report(report_text)

        for parameter, result in extracted.items():

            interpretation = generate_structured_interpretation(
                parameter,
                result
            )

            interpretation["Report ID"] = report_id

            structured_results.append(interpretation)

    structured_df = pd.DataFrame(structured_results)

    # -----------------------------------------
    # 2. Generate Related Findings
    # -----------------------------------------
    related_findings = []

    for report_id, report_group in structured_df.groupby("Report ID"):

        findings = detect_related_findings(report_group)

        related_findings.append({
            "Report ID": report_id,
            "Related Findings": findings
        })

    related_findings_df = pd.DataFrame(
        related_findings
    )

    # Convert list into readable text
    related_findings_df["Related Findings"] = (
        related_findings_df["Related Findings"]
        .apply(
            lambda x: "\n".join(
                f"• {finding}"
                for finding in x
            )
        )
    )

    # -----------------------------------------
    # 3. Create compact CBC summary
    # -----------------------------------------
    compact_summaries = []

    for report_id, report_group in structured_df.groupby("Report ID"):

        compact_summary = create_compact_cbc_summary(
            report_group
        )

        compact_summaries.append({
            "Report ID": report_id,
            "CBC Summary": compact_summary
        })

    compact_summary_df = pd.DataFrame(
        compact_summaries
    )

    # -----------------------------------------
    # 4. Create Overall CBC Summary
    # -----------------------------------------
    overall_summaries = []

    for report_id, report_group in structured_df.groupby("Report ID"):

        overall_summary = generate_overall_cbc_summary(
            report_group
        )

        overall_summaries.append({
            "Report ID": report_id,
            "Overall CBC Summary": overall_summary
        })

    overall_summary_df = pd.DataFrame(
        overall_summaries
    )

    # -----------------------------------------
    # 5. Merge everything together
    # -----------------------------------------
    final_report_df = (
        compact_summary_df
        .merge(
            overall_summary_df,
            on="Report ID",
            how="left"
        )
        .merge(
            related_findings_df,
            on="Report ID",
            how="left"
        )
    )

    return structured_df, final_report_df

In [101]:
all_structured_df, final_report_df = generate_final_cbc_report(
    cbc_df
)

In [102]:
print("Structured results:", len(all_structured_df))
print("Reports:", final_report_df["Report ID"].nunique())
print("Final columns:")
print(final_report_df.columns.tolist())

Structured results: 900
Reports: 100
Final columns:
['Report ID', 'CBC Summary', 'Overall CBC Summary', 'Related Findings']

In [103]:
display(
    final_report_df[
        [
            "Report ID",
            "CBC Summary",
            "Overall CBC Summary",
            "Related Findings"
        ]
    ].head(3)
)

,Report ID,CBC Summary,Overall CBC Summary,Related Findings
0,CBC_001,CBC Report: CBC_001\n\nHGB: 14.2 g/dL — Normal...,7 of 9 measured CBC parameters are within the ...,• NE% is high while LY% is low. This relative ...
1,CBC_002,CBC Report: CBC_002\n\nHGB: 11.9 g/dL — Low\nH...,7 of 9 measured CBC parameters are within the ...,• HGB and HCT are both below the provided refe...
2,CBC_003,CBC Report: CBC_003\n\nHGB: 11.0 g/dL — Low\nH...,4 of 9 measured CBC parameters are within the ...,• HGB and HCT are both below the provided refe...

In [111]:
def process_cbc_report(report_text, report_id="Unknown"):

    # -----------------------------------------
    # 1. Extract CBC parameters
    # -----------------------------------------
    extracted = extract_cbc_report(report_text)

    structured_results = []

    # -----------------------------------------
    # 2. Generate interpretations
    # -----------------------------------------
    for parameter, result in extracted.items():

        interpretation = generate_structured_interpretation(
            parameter,
            result
        )

        interpretation["Report ID"] = report_id

        structured_results.append(
            interpretation
        )

    # Convert to DataFrame
    structured_df = pd.DataFrame(
        structured_results
    )

    # -----------------------------------------
    # 3. Detect related findings
    # -----------------------------------------
    related_findings = detect_related_findings(
        structured_df
    )

    related_findings_text = "\n".join(
        f"• {finding}"
        for finding in related_findings
    )

    # -----------------------------------------
    # 4. Generate overall summary
    # -----------------------------------------
    overall_summary = generate_overall_cbc_summary(
        structured_df
    )

    # -----------------------------------------
    # 5. Generate compact CBC summary
    # -----------------------------------------
    compact_summary = create_compact_cbc_summary(
        structured_df
    )

    # -----------------------------------------
    # 6. Final report information
    # -----------------------------------------
    final_report = {
        "Report ID": report_id,
        "CBC Summary": compact_summary,
        "Overall CBC Summary": overall_summary,
        "Related Findings": related_findings_text
    }

    return structured_df, final_report

In [112]:
test_report = cbc_df[
    cbc_df["report_id"] == "CBC_001"
].iloc[0]

structured_result, final_result = process_cbc_report(
    test_report["raw_report_text"],
    test_report["report_id"]
)

print(final_result)

{'Report ID': 'CBC_001', 'CBC Summary': 'CBC Report: CBC_001\n\nHGB: 14.2 g/dL — Normal\nHCT: 41.0 % — Normal\nPLT: 244000.0 /µL — Normal\nMCV: 95.5 fL — Normal\nMCHC: 33.2 g/dL — Normal\nMCH: 30.8 pg — Normal\nRDW: 12.3 % — Normal\nNE%: 83.6 % — High\nLY%: 14.1 % — Low', 'Overall CBC Summary': '7 of 9 measured CBC parameters are within the provided reference ranges. The following parameter(s) are below the provided reference ranges: LY%. The following parameter(s) are above the provided reference ranges: NE%. These findings should be interpreted together with the rest of the CBC, symptoms, medical history and other clinical information.', 'Related Findings': '• NE% is high while LY% is low. This relative differential pattern should be interpreted together with the complete CBC and clinical context.'}